local MATCHUP_PANEL_DELAY = 0.85
--!strict
local Factory=require(script.Parent.MockModeService)
return Factory.new({Id="Career",Kicker="WRITE YOUR STORY",Title="CAREER",Subtitle="Create a player or manager and shape a long-form career.",Tabs={
	{Id="Saves",Label="SAVE SLOTS",Description="Choose a career save",Cards={}},
	{Id="Choose",Label="CHOOSE CAREER",Description="Select your journey",Cards={{Title="PLAYER CAREER",Subtitle="BECOME A VOLTRA ICON",Meta="Create and develop one player",Accent=true,Action={Label="CHOOSE PLAYER",TargetTab="CreatePlayer"}},{Title="MANAGER CAREER",Subtitle="BUILD A DYNASTY",Meta="Tactics, transfers and trophies",Action={Label="CHOOSE MANAGER",TargetTab="CreateManager"}}}},
	{Id="CreatePlayer",Label="CREATE PLAYER",Description="Player identity",Cards={{Title="ALEX VOLT",Subtitle="CAM • RIGHT FOOT",Meta="AURORA • #10",Accent=true,Action={Label="EDIT PLAYER",Operation="Select",Key="PlayerPreset",Item="Alex Volt"}},{Title="BEGIN CAREER",Subtitle="YOUR CLUB",Meta="PROSPECT CONTRACT",Action={Label="CREATE PLAYER SAVE",Operation="Create",Key="PlayerCareer",AfterTab="Dashboard",Success="Player career created.",Confirm=true}}}},
	{Id="CreateManager",Label="CREATE MANAGER",Description="Manager identity",Cards={{Title="MORGAN VALE",Subtitle="TACTICAL VISIONARY",Meta="VOLTARA • POSSESSION",Accent=true,Action={Label="EDIT MANAGER",Operation="Select",Key="ManagerPreset",Item="Morgan Vale"}},{Title="BEGIN CAREER",Subtitle="YOUR CLUB",Meta="3-YEAR CONTRACT",Action={Label="CREATE MANAGER SAVE",Operation="Create",Key="ManagerCareer",AfterTab="Dashboard",Success="Manager career created.",Confirm=true}}}},
	{Id="Dashboard",Label="DASHBOARD",Description="Season 2026/27",Cards={{Title="NEXT MATCH",Subtitle="VS PARIS ATHLETIC",Meta="LEAGUE • MATCHDAY 25",Accent=true,Action={Label="PLAY MATCH",Operation="ComingSoon",Message="Career match presentation is ready; gameplay remains disconnected."}},{Title="MANAGER RATING",Subtitle="84 • VERY GOOD",Meta="BOARD CONFIDENCE",Action={Label="VIEW OBJECTIVES",Operation="Toast",Message="Board objectives and confidence opened."}}}},
	{Id="Calendar",Label="CALENDAR",Description="February 2027",Cards={{Title="FEB 18",Subtitle="PARIS ATHLETIC",Meta="HOME • LEAGUE",Accent=true,Action={Label="MATCH DETAILS",Operation="Toast",Message="Calendar match details opened."}},{Title="FEB 22",Subtitle="RECOVERY DAY",Meta="SQUAD REST",Action={Label="EDIT SCHEDULE",Operation="Select",Key="Schedule",Item="Recovery Day"}}}},
	{Id="Training",Label="TRAINING",Description="Weekly development",Cards={{Title="CREATIVE ENGINE",Subtitle="PASSING • VISION • DRIBBLING",Meta="A GRADE TARGET",Action={Label="START TRAINING",Operation="ComingSoon",Message="Training drill flow is prepared for a later simulation system."}},{Title="DEVELOPMENT PLAN",Subtitle="LEVEL 14",Meta="2 SKILL POINTS",Accent=true,Action={Label="ALLOCATE POINTS",Operation="Select",Key="Development",Item="Creative Engine"}}}},
	{Id="Contracts",Label="CONTRACTS",Description="Career agreements",Cards={{Title="VOLTRA FC",Subtitle="2Y 4M REMAINING",Meta="€42K / WEEK",Accent=true,Action={Label="CONTRACT DETAILS",Operation="Toast",Message="Contract clauses and targets displayed."}},{Title="AGENT STATUS",Subtitle="OPEN TO OFFERS",Meta="TOP 5 LEAGUES",Action={Label="EDIT PREFERENCES",Operation="Toggle",Key="OpenToOffers"}}}},
	{Id="Transfers",Label="TRANSFERS",Description="Market and negotiations",Cards={{Title="TRANSFER HUB",Subtitle="3 SHORTLISTED",Meta="1 ACTIVE NEGOTIATION",Action={Label="OPEN HUB",Operation="Toast",Message="Transfer shortlist and negotiation mock opened."}},{Title="NO NEW OFFERS",Subtitle="CHECK BACK LATER",Meta="Agent monitoring market",Empty=true,Action={Label="REFRESH OFFERS",Operation="ComingSoon",Message="No new offers are available."}}}},
	{Id="Stats",Label="STATS",Description="Season performance",Cards={{Title="24 APPEARANCES",Subtitle="11 GOALS • 16 ASSISTS",Meta="8.2 AVG RATING",Accent=true,Action={Label="FULL STATISTICS",Operation="Toast",Message="Competition and match statistics opened."}},{Title="CAREER TOTAL",Subtitle="67 APPEARANCES",Meta="26 GOALS • 31 ASSISTS",Action={Label="CAREER RECORDS",Operation="Toast",Message="Career record book opened."}}}},
	{Id="Saves",Label="SAVE SLOTS",Description="Three local mock slots",Cards={{Title="SLOT 1",Subtitle="ALEX VOLT • 2026/27",Meta="LAST SAVED TODAY",Accent=true,Action={Label="LOAD SAVE",Operation="Select",Key="SaveSlot",Item="Slot 1"}},{Title="SLOT 2",Subtitle="EMPTY",Meta="Create a new career",Empty=true,Action={Label="NEW CAREER",Operation="CareerSetup",TargetTab="Choose"}},{Title="SLOT 3",Subtitle="EMPTY",Meta="Create a new career",Empty=true,Action={Label="NEW CAREER",Operation="CareerSetup",TargetTab="Choose"}}}},
}})
