--!strict
local Factory=require(script.Parent.MockModeService)
return Factory.new({Id="Clubs",Kicker="TOGETHER WE RISE",Title="VOLTRA CLUBS",Subtitle="Organize your club, squad and competitive calendar.",Tabs={
	{Id="Start",Label="CREATE / JOIN",Description="Find your club",Cards={{Title="CREATE CLUB",Subtitle="BUILD A NEW IDENTITY",Meta="Name • crest • region",Accent=true,Action={Label="CREATE CLUB",Operation="Create",Key="ClubCreated",AfterTab="Dashboard",Success="Club created." ,Confirm=true}},{Title="JOIN CLUB",Subtitle="SEARCH OR INVITE",Meta="Invite code supported",Action={Label="JOIN CLUB",Operation="ComingSoon",Message="Club search and invite-code placeholder opened."}}}},
	{Id="Dashboard",Label="DASHBOARD",Description="Voltage United",Cards={{Title="ELITE DIVISION",Subtitle="7TH • 31 POINTS",Meta="NEXT: NEON CITY",Accent=true,Action={Label="VIEW FIXTURE",TargetTab="Fixtures"}},{Title="CLUB REPUTATION",Subtitle="ELITE II",Meta="64% TO ELITE I",Action={Label="VIEW PROGRESS",Operation="Toast",Message="Club reputation breakdown opened."}}}},
	{Id="Members",Label="MEMBERS",Description="18 / 24 players",Cards={{Title="NOVA_7",Subtitle="CAPTAIN • ST",Meta="ONLINE",Accent=true,Action={Label="MEMBER DETAILS",Operation="Toast",Message="Captain permissions and stats displayed."}},{Title="KRYPTIC",Subtitle="VICE CAPTAIN • CM",Meta="IN MENU",Action={Label="MEMBER DETAILS",Operation="Toast",Message="Member permissions and stats displayed."}},{Title="OPEN SLOT",Subtitle="6 SPACES AVAILABLE",Meta="Grow the club",Empty=true,Action={Label="INVITE PLAYER",Operation="ComingSoon",Message="Player invite placeholder opened."}}}},
	{Id="Roles",Label="ROLES",Description="Positions and permissions",Cards={{Title="CAPTAIN",Subtitle="NOVA_7",Meta="FULL MATCH CONTROL",Action={Label="EDIT ROLE",Operation="Select",Key="Captain",Item="NOVA_7"}},{Title="STRIKER",Subtitle="2 / 3 ASSIGNED",Meta="One role available",Action={Label="ASSIGN POSITION",Operation="Select",Key="Striker",Item="Open Slot"}},{Title="GOALKEEPER",Subtitle="KRYPTIC_GK",Meta="STARTER",Action={Label="POSITION DETAILS",Operation="Toast",Message="Goalkeeper role requirements displayed."}}}},
	{Id="PlayerBuilder",Label="PLAYER BUILDER",Description="Level 1 to 100 specialist progression",Cards={{Title="CREATE YOUR PRO",Subtitle="60 OVR • 20 STARTING ATTRIBUTE POINTS",Meta="Position • appearance • preferred foot",Accent=true,Action={Label="PLAYER CREATION",Operation="Toast",Message="Pro profile fields are ready in the server profile."}},{Title="ATTRIBUTE LAB",Subtitle="PACE • SHOOTING • PASSING • DRIBBLING",Meta="DEFENDING • PHYSICAL • GOALKEEPING",Action={Label="SPEND POINTS",Operation="Toast",Message="Attribute caps depend on position and selected build path."}},{Title="BUILD PATH",Subtitle="UNLOCKS AT LEVEL 20",Meta="Perks every 5 levels • Prestige at 100",Action={Label="VIEW BUILD PATHS",Operation="Toast",Message="Poacher, playmaker, stopper, fullback and goalkeeper paths loaded."}}}},
	{Id="Fixtures",Label="FIXTURES",Description="Club match calendar",Cards={{Title="VS NEON CITY",Subtitle="TODAY • 20:30",Meta="CLUB LEAGUE",Accent=true,Action={Label="MATCH LOBBY",Operation="ComingSoon",Message="Club match lobby is ready for later gameplay connection."}},{Title="VS ZERO ATHLETIC",Subtitle="SAT • 18:00",Meta="CLUB CUP",Action={Label="FIXTURE DETAILS",Operation="Toast",Message="Fixture details and availability opened."}}}},
	{Id="League",Label="LEAGUE TABLE",Description="Elite Division",Cards={{Title="#1  NIGHT CITY",Subtitle="42 POINTS",Meta="+24 GD",Accent=true,Action={Label="FULL TABLE",Operation="Toast",Message="Full 12-club league table opened."}},{Title="#7  VOLTAGE UNITED",Subtitle="31 POINTS",Meta="+8 GD",Action={Label="FORM GUIDE",Operation="Toast",Message="Recent form: W W D L W"}}}},
	{Id="Trophies",Label="TROPHIES",Description="Club honours",Cards={{Title="VOLTRA CUP",Subtitle="SEASON 02",Meta="CHAMPIONS",Accent=true,Action={Label="VIEW TROPHY",Operation="Toast",Message="Voltra Cup trophy presentation opened."}},{Title="EMPTY CABINET SLOT",Subtitle="NEXT TROPHY AWAITS",Meta="Compete this season",Empty=true,Action={Label="VIEW COMPETITIONS",Operation="Toast",Message="Available club competitions displayed."}}}},
	{Id="Settings",Label="CLUB SETTINGS",Description="Identity and access",Cards={{Title="JOIN POLICY",Subtitle="INVITE ONLY",Meta="Captain approval",Action={Label="CHANGE POLICY",Operation="Toggle",Key="OpenJoin"}},{Title="PRIMARY KIT",Subtitle="HOME KIT",Meta="ACTIVE",Action={Label="EDIT CLUB KIT",Operation="ComingSoon",Message="Club kit editor placeholder opened."}},{Title="CLUB MANAGEMENT",Subtitle="SAVE CHANGES",Meta="Session mock data",Accent=true,Action={Label="SAVE CLUB",Operation="Save"}}}},
}})
