--!strict
local Factory = require(script.Parent.MockModeService)
return Factory.new({Id="Play",Kicker="CHOOSE YOUR BATTLE",Title="PLAY",Subtitle="Configure a match flow before entering the pitch.",Tabs={
	{Id="Quick",Label="QUICK MATCH",Description="Fast local setup",Cards={{Title="QUICK MATCH",Subtitle="VOLTRA FC VS NIGHT CITY",Meta="6 MIN • CLEAR • COMPETITIVE",Accent=true,Action={Label="CONFIGURE",TargetTab="MatchSettings"}}}},
	{Id="Private",Label="PRIVATE MATCH",Description="Invite-only lobby",Cards={{Title="CREATE LOBBY",Subtitle="PRIVATE CODE",Meta="0 / 2 PLAYERS",Action={Label="CREATE PRIVATE MATCH",Operation="ComingSoon",Message="Private lobby created locally. Networking connects here later."}},{Title="JOIN LOBBY",Subtitle="ENTER INVITE CODE",Meta="No code entered",Empty=true,Action={Label="ENTER CODE",Operation="ComingSoon",Message="Invite code input placeholder opened."}}}},
	{Id="Training",Label="TRAINING GROUND",Description="Practice configuration",Cards={{Title="FREE TRAINING",Subtitle="OPEN PITCH",Meta="NO OPPONENT",Action={Label="ENTER TRAINING",Operation="ComingSoon",Message="Training Ground is configured but gameplay is intentionally disabled."}},{Title="SET PIECES",Subtitle="FREE KICKS & PENALTIES",Meta="CUSTOM POSITION",Action={Label="SET UP DRILL",Operation="Select",Key="Training",Item="Set Pieces"}}}},
	{Id="MatchSettings",Label="MATCH SETTINGS",Description="Rules and presentation",Cards={{Title="MATCH LENGTH",Subtitle="6 MINUTES",Meta="Competitive preset",Action={Label="CHANGE",Operation="Select",Key="Length",Item="6 Minutes"}},{Title="DIFFICULTY",Subtitle="WORLD CLASS",Meta="CPU opponent",Action={Label="CHANGE",Operation="Select",Key="Difficulty",Item="World Class"}},{Title="NEXT STEP",Subtitle="SELECT TEAMS",Meta="Settings ready",Accent=true,Action={Label="TEAM SELECT",TargetTab="TeamSelect"}}}},
	{Id="TeamSelect",Label="TEAM SELECT",Description="Choose both sides",Cards={{Title="HOME",Subtitle="VOLTRA FC",Meta="OVR 89",Accent=true,Action={Label="SELECT HOME",Operation="Select",Key="HomeTeam",Item="Voltra FC"}},{Title="AWAY",Subtitle="NIGHT CITY",Meta="OVR 87",Action={Label="SELECT AWAY",Operation="Select",Key="AwayTeam",Item="Night City"}},{Title="CONTINUE",Subtitle="TEAMS LOCKED",Meta="Select stadium",Action={Label="STADIUM SELECT",TargetTab="StadiumSelect"}}}},
	{Id="StadiumSelect",Label="STADIUM SELECT",Description="Match venue",Cards={{Title="VOLTAGE ARENA",Subtitle="CAPACITY 58,000",Meta="NIGHT • CLEAR",Accent=true,Action={Label="SELECT STADIUM",Operation="Select",Key="Stadium",Item="Voltage Arena"}},{Title="CONTINUE",Subtitle="VENUE READY",Meta="Select kits",Action={Label="KIT SELECT",TargetTab="KitSelect"}}}},
	{Id="KitSelect",Label="KIT SELECT",Description="Avoid kit clashes",Cards={{Title="HOME KIT",Subtitle="VOLTAGE BLACK",Meta="NEON TRIM",Action={Label="SELECT KIT",Operation="Select",Key="HomeKit",Item="Voltage Black"}},{Title="AWAY KIT",Subtitle="SILVER STATIC",Meta="GRAPHITE TRIM",Action={Label="SELECT KIT",Operation="Select",Key="AwayKit",Item="Silver Static"}},{Title="CONTINUE",Subtitle="NO KIT CLASH",Meta="Ready check",Accent=true,Action={Label="READY SCREEN",TargetTab="Ready"}}}},
	{Id="Ready",Label="READY",Description="Final match check",Cards={{Title="VOLTRA FC VS NIGHT CITY",Subtitle="VOLTAGE ARENA",Meta="6 MIN • WORLD CLASS",Accent=true,Action={Label="START MATCH",Operation="ComingSoon",Message="Match setup saved. Gameplay connection will be added in a later milestone.",Loading=true}},{Title="EDIT SETUP",Subtitle="RETURN TO SETTINGS",Meta="All choices retained",Action={Label="BACK TO SETTINGS",TargetTab="MatchSettings"}}}},
}})
