--!strict
local Factory = require(script.Parent.MockModeService)

return Factory.new({
	Id = "Settings",
	Kicker = "MAKE IT YOURS",
	Title = "SETTINGS",
	Subtitle = "Tune input, presentation, accessibility and account preferences.",
	Tabs = {
		{Id = "Controls", Label = "CONTROLS", Description = "Input and assistance", Cards = {
			{Title = "COMPETITIVE PRESET", Subtitle = "ACTIVE", Meta = "Manual switching / assisted passing", Accent = true, Action = {Label = "CHANGE PRESET", Operation = "Select", Key = "ControlPreset", Item = "Competitive"}},
			{Title = "TIMED FINISHING", Subtitle = "ON", Meta = "LMB double input", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "TimedFinishing"}},
			{Title = "TRAINER", Subtitle = "BASIC", Meta = "Contextual match prompts", Accent = true, Action = {Label = "SELECT BASIC", Operation = "Select", Key = "Trainer", Item = "Basic"}},
			{Title = "TRAINER FULL", Subtitle = "ALL PROMPTS", Meta = "Show every contextual action", Action = {Label = "SELECT FULL", Operation = "Select", Key = "Trainer", Item = "Full"}},
			{Title = "TRAINER OFF", Subtitle = "HIDDEN", Meta = "Disable trainer prompts", Action = {Label = "SELECT OFF", Operation = "Select", Key = "Trainer", Item = "Off"}},
			{Title = "PASS RECEIVER SWITCH", Subtitle = "ASSISTED", Meta = "Switch shortly after a targeted pass", Accent = true, Action = {Label = "SELECT ASSISTED", Operation = "Select", Key = "PassReceiverAutoSwitch", Item = "Assisted"}},
			{Title = "PASS SWITCH INSTANT", Subtitle = "INSTANT", Meta = "Control receiver as the ball leaves", Action = {Label = "SELECT INSTANT", Operation = "Select", Key = "PassReceiverAutoSwitch", Item = "Instant"}},
			{Title = "PASS SWITCH OFF", Subtitle = "OFF", Meta = "Keep control of the passer", Action = {Label = "SELECT OFF", Operation = "Select", Key = "PassReceiverAutoSwitch", Item = "Off"}},
			{Title = "RECEIVER ASSIST", Subtitle = "LIGHT", Meta = "Briefly guides the receiver until WASD input", Accent = true, Action = {Label = "SELECT LIGHT", Operation = "Select", Key = "ReceiverAssist", Item = "Light"}},
			{Title = "RECEIVER ASSIST FULL", Subtitle = "ASSISTED", Meta = "Longer automatic intercept guidance", Action = {Label = "SELECT ASSISTED", Operation = "Select", Key = "ReceiverAssist", Item = "Assisted"}},
			{Title = "RECEIVER ASSIST OFF", Subtitle = "OFF", Meta = "Manual receiver movement immediately", Action = {Label = "SELECT OFF", Operation = "Select", Key = "ReceiverAssist", Item = "Off"}},
			{Title = "KEYBINDS", Subtitle = "WASD MOVE / SHIFT SPRINT", Meta = "LMB shoot / RMB pass / E tackle / F slide / R block", Action = {Label = "VIEW ALL KEYBINDS", Operation = "Toast", Message = "WASD Move / Shift Sprint / Q Switch / LMB Shoot / RMB Pass / Alt Manual Lob / Ctrl Manual Pass / E Tackle / F Slide / R Block / C Dribble"}},
		}},
		{Id = "Audio", Label = "AUDIO", Description = "Game and music mix", Cards = {
			{Title = "MASTER VOLUME", Subtitle = "80%", Meta = "ALL CHANNELS", Action = {Label = "ADJUST", Operation = "Select", Key = "MasterVolume", Item = "80%"}},
			{Title = "MENU MUSIC", Subtitle = "ON", Meta = "VOLTRA soundtrack", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "MenuMusic"}},
		}},
		{Id = "Graphics", Label = "GRAPHICS", Description = "Display quality", Cards = {
			{Title = "QUALITY PRESET", Subtitle = "HIGH", Meta = "Automatic performance scaling", Accent = true, Action = {Label = "CHANGE QUALITY", Operation = "Select", Key = "Graphics", Item = "High"}},
			{Title = "MOTION EFFECTS", Subtitle = "ON", Meta = "UI glow and transitions", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "MotionEffects"}},
			{Title = "PERFORMANCE MODE", Subtitle = "OFF", Meta = "Reduces decorative effects", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "PerformanceMode"}},
		}},
		{Id = "Camera", Label = "CAMERA", Description = "View and response", Cards = {
			{Title = "CAMERA PRESET", Subtitle = "WIDE BROADCAST", Meta = "Default 1.5x original broadcast distance", Accent = true, Action = {Label = "SELECT WIDE", Operation = "Select", Key = "CameraPreset", Item = "WideBroadcast"}},
			{Title = "CAMERA PRESET CLOSE", Subtitle = "CLOSE BROADCAST", Meta = "2.5x closer sideline match view", Action = {Label = "SELECT CLOSE", Operation = "Select", Key = "CameraPreset", Item = "CloseBroadcast"}},
			{Title = "CAMERA PRESET END", Subtitle = "END TO END", Meta = "Goal-to-goal tactical direction", Action = {Label = "SELECT END", Operation = "Select", Key = "CameraPreset", Item = "End to End"}},
			{Title = "CAMERA PRESET PRO", Subtitle = "PRO", Meta = "Player-follow camera", Action = {Label = "SELECT PRO", Operation = "Select", Key = "CameraPreset", Item = "Pro"}},
			{Title = "CAMERA ZOOM", Subtitle = "WIDE", Meta = "Default expanded pitch view", Accent = true, Action = {Label = "SELECT WIDE", Operation = "Select", Key = "CameraZoomMode", Item = "Wide"}},
			{Title = "CAMERA ZOOM CLOSE", Subtitle = "CLOSE", Meta = "More player detail", Action = {Label = "SELECT CLOSE", Operation = "Select", Key = "CameraZoomMode", Item = "Close"}},
			{Title = "CAMERA ZOOM DEFAULT", Subtitle = "DEFAULT", Meta = "Balanced broadcast view", Action = {Label = "SELECT DEFAULT", Operation = "Select", Key = "CameraZoomMode", Item = "Default"}},
			{Title = "CAMERA ZOOM TACTICAL", Subtitle = "TACTICAL WIDE", Meta = "Maximum team-shape visibility", Action = {Label = "SELECT TACTICAL", Operation = "Select", Key = "CameraZoomMode", Item = "Tactical Wide"}},
			{Title = "BROADCAST HEIGHT", Subtitle = "178 STUDS", Meta = "Wide crowd-level view", Action = {Label = "STANDARD HEIGHT", Operation = "Select", Key = "BroadcastHeight", Item = "178"}},
			{Title = "BROADCAST HEIGHT HIGH", Subtitle = "208 STUDS", Meta = "See more of the pitch", Action = {Label = "HIGHER CAMERA", Operation = "Select", Key = "BroadcastHeight", Item = "208"}},
			{Title = "BROADCAST FOV", Subtitle = "50 FOV", Meta = "Wide co-op framing", Action = {Label = "STANDARD FOV", Operation = "Select", Key = "BroadcastZoom", Item = "50"}},
			{Title = "BROADCAST FOV WIDE", Subtitle = "55 FOV", Meta = "Maximum tactical width", Action = {Label = "WIDER VIEW", Operation = "Select", Key = "BroadcastZoom", Item = "55"}},
			{Title = "CAMERA SPEED", Subtitle = "SMOOTH", Meta = "Broadcast-style damping", Action = {Label = "SELECT SMOOTH", Operation = "Select", Key = "CameraSpeed", Item = "1"}},
			{Title = "CAMERA SPEED FAST", Subtitle = "RESPONSIVE", Meta = "Tracks counters more quickly", Action = {Label = "SELECT FAST", Operation = "Select", Key = "CameraSpeed", Item = "1.35"}},
			{Title = "CAMERA SIDE", Subtitle = "NEAR SIDE", Meta = "Camera from the home touchline", Action = {Label = "SELECT NEAR", Operation = "Select", Key = "CameraSide", Item = "Near"}},
			{Title = "CAMERA SIDE FAR", Subtitle = "FAR SIDE", Meta = "Flip to the opposite stand", Action = {Label = "SELECT FAR", Operation = "Select", Key = "CameraSide", Item = "Far"}},
			{Title = "MINIMAP", Subtitle = "MEDIUM", Meta = "Full tactical overview", Action = {Label = "SELECT MEDIUM", Operation = "Select", Key = "Minimap", Item = "Medium"}},
			{Title = "MINIMAP SMALL", Subtitle = "COMPACT", Meta = "Smaller bottom-center radar", Action = {Label = "SELECT SMALL", Operation = "Select", Key = "Minimap", Item = "Small"}},
			{Title = "MINIMAP OFF", Subtitle = "HIDDEN", Meta = "Disable the match minimap", Action = {Label = "TURN OFF", Operation = "Select", Key = "Minimap", Item = "Off"}},
			{Title = "MINIMAP ORIENTATION", Subtitle = "BROADCAST", Meta = "Mirrors the selected camera stand", Action = {Label = "SELECT BROADCAST", Operation = "Select", Key = "MinimapOrientation", Item = "Broadcast"}},
			{Title = "MINIMAP ATTACKING", Subtitle = "ATTACKING DIRECTION", Meta = "Always attack left to right", Action = {Label = "SELECT ATTACKING", Operation = "Select", Key = "MinimapOrientation", Item = "Attacking Direction"}},
			{Title = "PLAYER NAMES", Subtitle = "ACTIVE ONLY", Meta = "Show the controlled player", Accent = true, Action = {Label = "ACTIVE ONLY", Operation = "Select", Key = "PlayerNames", Item = "Active Only"}},
			{Title = "PLAYER NAMES OFF", Subtitle = "CLEAN PITCH", Meta = "Hide every player name", Action = {Label = "SELECT OFF", Operation = "Select", Key = "PlayerNames", Item = "Off"}},
			{Title = "PLAYER NAMES ALL", Subtitle = "FULL TEAM LABELS", Meta = "Show every player name", Action = {Label = "SELECT ALL", Operation = "Select", Key = "PlayerNames", Item = "All"}},
			{Title = "CAMERA SHAKE", Subtitle = "LOW", Meta = "Goals and tackles", Action = {Label = "CHANGE", Operation = "Select", Key = "CameraShake", Item = "Low"}},
			{Title = "INVERT Y", Subtitle = "OFF", Meta = "Mouse and controller", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "InvertY"}},
		}},
		{Id = "Accessibility", Label = "ACCESSIBILITY", Description = "Clarity and comfort", Cards = {
			{Title = "HIGH CONTRAST", Subtitle = "OFF", Meta = "Enhanced UI separation", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "HighContrast"}},
			{Title = "REDUCED MOTION", Subtitle = "OFF", Meta = "Shorter transitions", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "ReducedMotion"}},
			{Title = "TEXT SCALE", Subtitle = "100%", Meta = "Interface typography", Action = {Label = "CHANGE SCALE", Operation = "Select", Key = "TextScale", Item = "100%"}},
		}},
		{Id = "Account", Label = "ACCOUNT", Description = "Session and privacy", Cards = {
			{Title = "VOLT_X", Subtitle = "ACCOUNT CONNECTED", Meta = "EU WEST", Accent = true, Action = {Label = "ACCOUNT DETAILS", Operation = "Toast", Message = "Account ID and region information displayed."}},
			{Title = "CROSS-PLAY", Subtitle = "ENABLED", Meta = "All supported platforms", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "Crossplay"}},
			{Title = "SAVE SETTINGS", Subtitle = "SERVER PROFILE", Meta = "Saved for your next session", Action = {Label = "SAVE CHANGES", Operation = "Save", Confirm = true}},
			{Title = "RESET LAUNCH PROFILE", Subtitle = "FRESH SAVE", Meta = "Studio only", Action = {Label = "RESET PROFILE", Operation = "Developer", ServerAction = "DeveloperResetProfile", Confirm = true}},
		}},
	},
}, {
	Owned = {},
	Equipped = {},
	Claimed = {},
	Selections = {CameraPreset = "WideBroadcast", CameraZoomMode = "Wide", PlayerNames = "Active Only", Trainer = "Basic", PassReceiverAutoSwitch = "Assisted", ReceiverAssist = "Light", Minimap = "Medium", MinimapOrientation = "Broadcast", BroadcastHeight = "178", BroadcastZoom = "50", CameraSpeed = "1", CameraSide = "Near"},
	Values = {TimedFinishing = true, MenuMusic = true, MotionEffects = true, PerformanceMode = false, InvertY = false, HighContrast = false, ReducedMotion = false, Crossplay = true, CameraPreset = "WideBroadcast", PlayerNames = "Active Only", Trainer = "Basic", PassReceiverAutoSwitch = "Assisted", ReceiverAssist = "Light", Minimap = "Medium", MinimapOrientation = "Broadcast", BroadcastHeight = "178", BroadcastZoom = "50", CameraSpeed = "1", CameraSide = "Near"},
})
