--!strict
local Factory = require(script.Parent.MockModeService)

return Factory.new({
	Id = "Settings",
	Kicker = "MAKE IT YOURS",
	Title = "SETTINGS",
	Subtitle = "Tune input, presentation, accessibility and account preferences.",
	Tabs = {
		{Id = "Controls", Label = "CONTROLS", Description = "Input and assistance", Cards = {
			{Title = "COMPETITIVE PRESET", Subtitle = "ACTIVE", Meta = "Manual switching / assisted passing", Accent = true, Action = {Label = "CHANGE PRESET", Operation = "Select", Key = "ControlPreset", Item = "Competitive"}},
			{Title = "TIMED FINISHING", Subtitle = "ON", Meta = "LMB double input", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "TimedFinishing"}},
			{Title = "TRAINER", Subtitle = "BASIC", Meta = "Contextual match prompts", Accent = true, Action = {Label = "SELECT BASIC", Operation = "Select", Key = "Trainer", Item = "Basic"}},
			{Title = "TRAINER FULL", Subtitle = "ALL PROMPTS", Meta = "Show every contextual action", Action = {Label = "SELECT FULL", Operation = "Select", Key = "Trainer", Item = "Full"}},
			{Title = "TRAINER OFF", Subtitle = "HIDDEN", Meta = "Disable trainer prompts", Action = {Label = "SELECT OFF", Operation = "Select", Key = "Trainer", Item = "Off"}},
			{Title = "RECEIVER SWITCH", Subtitle = "STANDARD", Meta = "Switch near the final quarter of pass travel", Accent = true, Action = {Label = "SELECT STANDARD", Operation = "Select", Key = "PassReceiverAutoSwitch", Item = "Standard"}},
			{Title = "RECEIVER SWITCH NEWCOMER", Subtitle = "EARLIER", Meta = "Readable assisted switch with a generous first touch", Action = {Label = "SELECT NEWCOMER", Operation = "Select", Key = "PassReceiverAutoSwitch", Item = "Newcomer"}},
			{Title = "RECEIVER SWITCH MANUAL", Subtitle = "MANUAL", Meta = "Keep control until you switch players", Action = {Label = "SELECT MANUAL", Operation = "Select", Key = "PassReceiverAutoSwitch", Item = "Manual"}},
			{Title = "MANUAL PASS SWITCH", Subtitle = "STANDARD", Meta = "Switch to the teammate collecting your manual pass", Accent = true, Action = {Label = "SELECT STANDARD", Operation = "Select", Key = "ManualPassAutoSwitch", Item = "Standard"}},
			{Title = "MANUAL PASS SWITCH OFF", Subtitle = "MANUAL", Meta = "Manual passes keep control of the passer", Action = {Label = "SELECT MANUAL", Operation = "Select", Key = "ManualPassAutoSwitch", Item = "Manual"}},
			{Title = "RECEIVER ASSIST", Subtitle = "STANDARD", Meta = "Light guidance that stops on decisive movement", Accent = true, Action = {Label = "SELECT STANDARD", Operation = "Select", Key = "ReceiverAssistMode", Item = "Standard"}},
			{Title = "RECEIVER ASSIST NEWCOMER", Subtitle = "NEWCOMER", Meta = "Longer guidance and a more forgiving first touch", Action = {Label = "SELECT NEWCOMER", Operation = "Select", Key = "ReceiverAssistMode", Item = "Newcomer"}},
			{Title = "RECEIVER ASSIST MANUAL", Subtitle = "MANUAL", Meta = "No automatic movement toward the pass", Action = {Label = "SELECT MANUAL", Operation = "Select", Key = "ReceiverAssistMode", Item = "Manual"}},
			{Title = "MOBILE SPRINT", Subtitle = "TOGGLE", Meta = "Tap once to request sprint", Action = {Label = "SELECT TOGGLE", Operation = "Select", Key = "MobileSprintMode", Item = "Toggle"}},
			{Title = "MOBILE SPRINT HOLD", Subtitle = "HOLD", Meta = "Sprint only while the button is held", Action = {Label = "SELECT HOLD", Operation = "Select", Key = "MobileSprintMode", Item = "Hold"}},
			{Title = "MOBILE ACTION HAND", Subtitle = "RIGHT", Meta = "Action controls use the right side", Action = {Label = "SELECT RIGHT", Operation = "Select", Key = "MobileControlHandedness", Item = "Right"}},
			{Title = "MOBILE ACTION HAND LEFT", Subtitle = "LEFT", Meta = "Action controls use the left side", Action = {Label = "SELECT LEFT", Operation = "Select", Key = "MobileControlHandedness", Item = "Left"}},
			{Title = "KEYBINDS", Subtitle = "WASD MOVE / SHIFT SPRINT", Meta = "LMB shot / RMB ground / E + RMB through / Alt lob / Ctrl manual pass", Action = {Label = "VIEW ALL KEYBINDS", Operation = "Toast", Message = "WASD Move / Shift Sprint / Q Switch / LMB Shot / RMB Ground Pass / E + RMB Through Pass / Alt Lob / Ctrl Manual Ground Pass / E Tackle / F Slide / R Block / C Dribble"}},
		}},
		{Id = "Audio", Label = "AUDIO", Description = "Game and music mix", Cards = {
			{Title = "MASTER VOLUME", Subtitle = "80%", Meta = "ALL CHANNELS", Action = {Label = "ADJUST", Operation = "Select", Key = "MasterVolume", Item = "80%"}},
			{Title = "MENU MUSIC", Subtitle = "ON", Meta = "VOLTRA soundtrack", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "MenuMusic"}},
		}},
		{Id = "Graphics", Label = "GRAPHICS", Description = "Display quality", Cards = {
			{Title = "QUALITY PRESET", Subtitle = "HIGH", Meta = "Automatic performance scaling", Accent = true, Action = {Label = "CHANGE QUALITY", Operation = "Select", Key = "Graphics", Item = "High"}},
			{Title = "MOTION EFFECTS", Subtitle = "ON", Meta = "UI glow and transitions", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "MotionEffects"}},
			{Title = "PERFORMANCE MODE", Subtitle = "OFF", Meta = "Reduces decorative effects", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "PerformanceMode"}},
			{Title = "IMMERSIVE PRESENTATION", Subtitle = "OFF", Meta = "Use broadcast presentation when the mode allows it", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "ImmersivePresentation"}},
		}},
		{Id = "Camera", Label = "CAMERA", Description = "View and response", Cards = {
			{Title = "CAMERA PRESET", Subtitle = "AUTO", Meta = "Uses the recommended view for your device", Accent = true, Action = {Label = "SELECT AUTO", Operation = "Select", Key = "CameraPreset", Item = "Auto"}},
			{Title = "CAMERA PRESET TACTICAL", Subtitle = "TACTICAL", Meta = "High sideline view with full team-shape visibility", Action = {Label = "SELECT TACTICAL", Operation = "Select", Key = "CameraPreset", Item = "Tactical"}},
			{Title = "CAMERA PRESET PRO", Subtitle = "PRO", Meta = "Player-follow camera", Action = {Label = "SELECT PRO", Operation = "Select", Key = "CameraPreset", Item = "Pro"}},
			{Title = "CAMERA ZOOM", Subtitle = "WIDE", Meta = "Default expanded pitch view", Accent = true, Action = {Label = "SELECT WIDE", Operation = "Select", Key = "CameraZoomMode", Item = "Wide"}},
			{Title = "CAMERA ZOOM CLOSE", Subtitle = "CLOSE", Meta = "More player detail", Action = {Label = "SELECT CLOSE", Operation = "Select", Key = "CameraZoomMode", Item = "Close"}},
			{Title = "CAMERA ZOOM MODERATE", Subtitle = "MODERATE", Meta = "Balanced player and pitch visibility", Action = {Label = "SELECT MODERATE", Operation = "Select", Key = "CameraZoomMode", Item = "Moderate"}},
			{Title = "BROADCAST HEIGHT", Subtitle = "178 STUDS", Meta = "Wide crowd-level view", Action = {Label = "STANDARD HEIGHT", Operation = "Select", Key = "BroadcastHeight", Item = "178"}},
			{Title = "BROADCAST HEIGHT HIGH", Subtitle = "208 STUDS", Meta = "See more of the pitch", Action = {Label = "HIGHER CAMERA", Operation = "Select", Key = "BroadcastHeight", Item = "208"}},
			{Title = "BROADCAST FOV", Subtitle = "50 FOV", Meta = "Wide co-op framing", Action = {Label = "STANDARD FOV", Operation = "Select", Key = "BroadcastZoom", Item = "50"}},
			{Title = "BROADCAST FOV WIDE", Subtitle = "55 FOV", Meta = "Maximum tactical width", Action = {Label = "WIDER VIEW", Operation = "Select", Key = "BroadcastZoom", Item = "55"}},
			{Title = "CAMERA SPEED", Subtitle = "SMOOTH", Meta = "Broadcast-style damping", Action = {Label = "SELECT SMOOTH", Operation = "Select", Key = "CameraSpeed", Item = "1"}},
			{Title = "CAMERA SPEED FAST", Subtitle = "RESPONSIVE", Meta = "Tracks counters more quickly", Action = {Label = "SELECT FAST", Operation = "Select", Key = "CameraSpeed", Item = "1.35"}},
			{Title = "CAMERA SIDE", Subtitle = "NEAR SIDE", Meta = "Camera from the home touchline", Action = {Label = "SELECT NEAR", Operation = "Select", Key = "CameraSide", Item = "Near"}},
			{Title = "CAMERA SIDE FAR", Subtitle = "FAR SIDE", Meta = "Flip to the opposite stand", Action = {Label = "SELECT FAR", Operation = "Select", Key = "CameraSide", Item = "Far"}},
			{Title = "MINIMAP", Subtitle = "MEDIUM", Meta = "Full tactical overview", Action = {Label = "SELECT MEDIUM", Operation = "Select", Key = "Minimap", Item = "Medium"}},
			{Title = "MINIMAP SMALL", Subtitle = "COMPACT", Meta = "Smaller bottom-center radar", Action = {Label = "SELECT SMALL", Operation = "Select", Key = "Minimap", Item = "Small"}},
			{Title = "MINIMAP OFF", Subtitle = "HIDDEN", Meta = "Disable the match minimap", Action = {Label = "TURN OFF", Operation = "Select", Key = "Minimap", Item = "Off"}},
			{Title = "MINIMAP ORIENTATION", Subtitle = "BROADCAST", Meta = "Mirrors the selected camera stand", Action = {Label = "SELECT BROADCAST", Operation = "Select", Key = "MinimapOrientation", Item = "Broadcast"}},
			{Title = "MINIMAP ATTACKING", Subtitle = "ATTACKING DIRECTION", Meta = "Always attack left to right", Action = {Label = "SELECT ATTACKING", Operation = "Select", Key = "MinimapOrientation", Item = "Attacking Direction"}},
			{Title = "PLAYER NAMES", Subtitle = "ACTIVE ONLY", Meta = "Show the controlled player", Accent = true, Action = {Label = "ACTIVE ONLY", Operation = "Select", Key = "PlayerNames", Item = "Active Only"}},
			{Title = "PLAYER NAMES OFF", Subtitle = "CLEAN PITCH", Meta = "Hide every player name", Action = {Label = "SELECT OFF", Operation = "Select", Key = "PlayerNames", Item = "Off"}},
			{Title = "PLAYER NAMES ALL", Subtitle = "FULL TEAM LABELS", Meta = "Show every player name", Action = {Label = "SELECT ALL", Operation = "Select", Key = "PlayerNames", Item = "All"}},
			{Title = "CAMERA SHAKE", Subtitle = "LOW", Meta = "Goals and tackles", Action = {Label = "CHANGE", Operation = "Select", Key = "CameraShake", Item = "Low"}},
			{Title = "INVERT Y", Subtitle = "OFF", Meta = "Mouse and controller", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "InvertY"}},
		}},
		{Id = "Accessibility", Label = "ACCESSIBILITY", Description = "Clarity and comfort", Cards = {
			{Title = "HIGH CONTRAST", Subtitle = "OFF", Meta = "Enhanced UI separation", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "HighContrast"}},
			{Title = "REDUCED MOTION", Subtitle = "OFF", Meta = "Shorter transitions", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "ReducedMotion"}},
			{Title = "TEXT SCALE", Subtitle = "100%", Meta = "Interface typography", Action = {Label = "CHANGE SCALE", Operation = "Select", Key = "TextScale", Item = "100%"}},
		}},
		{Id = "Account", Label = "ACCOUNT", Description = "Session and privacy", Cards = {
			{Title = "VOLT_X", Subtitle = "ACCOUNT CONNECTED", Meta = "EU WEST", Accent = true, Action = {Label = "ACCOUNT DETAILS", Operation = "Toast", Message = "Account ID and region information displayed."}},
			{Title = "CROSS-PLAY", Subtitle = "ENABLED", Meta = "All supported platforms", Action = {Label = "TOGGLE", Operation = "Toggle", Key = "Crossplay"}},
			{Title = "SAVE SETTINGS", Subtitle = "SERVER PROFILE", Meta = "Saved for your next session", Action = {Label = "SAVE CHANGES", Operation = "Save", Confirm = true}},
			{Title = "RESET LAUNCH PROFILE", Subtitle = "FRESH SAVE", Meta = "Studio only", Action = {Label = "RESET PROFILE", Operation = "Developer", ServerAction = "DeveloperResetProfile", Confirm = true}},
			{Title = "WORLD CUP ONBOARDING", Subtitle = "GUIDED START", Meta = "Replay the direct World Cup first-match guide", Action = {Label = "OPEN GUIDE", Operation = "ShowTutorial"}},
		}},
	},
}, {
	Owned = {},
	Equipped = {},
	Claimed = {},
	Selections = {CameraPreset = "Auto", CameraZoomMode = "Moderate", PlayerNames = "Active Only", Trainer = "Basic", PassReceiverAutoSwitch = "Standard", ManualPassAutoSwitch = "Manual", ReceiverAssistMode = "Standard", MobileSprintMode = "Toggle", MobileControlHandedness = "Right", Minimap = "Medium", MinimapOrientation = "Broadcast", BroadcastHeight = "178", BroadcastZoom = "50", CameraSpeed = "1", CameraSide = "Near"},
	Values = {TimedFinishing = true, MenuMusic = true, MotionEffects = true, PerformanceMode = false, ImmersivePresentation = false, InvertY = false, HighContrast = false, ReducedMotion = false, Crossplay = true, CameraPreset = "Auto", CameraZoomMode = "Moderate", PlayerNames = "Active Only", Trainer = "Basic", PassReceiverAutoSwitch = "Standard", ManualPassAutoSwitch = "Manual", ReceiverAssistMode = "Standard", MobileSprintMode = "Toggle", MobileControlHandedness = "Right", Minimap = "Medium", MinimapOrientation = "Broadcast", BroadcastHeight = "178", BroadcastZoom = "50", CameraSpeed = "1", CameraSide = "Near", TutorialComplete = false, TutorialStep = 1, TutorialDevice = ""},
})
