--!strict
local Factory=require(script.Parent.MockModeService)
return Factory.new({Id="Store",Kicker="CURATED FOR THE ELITE",Title="VOLTRA STORE",Subtitle="Premium identity items and curated packs.",Tabs={
	{Id="Featured",Label="FEATURED",Description="Limited Voltage Afterdark drop",Cards={{Title="VOLTAGE AFTERDARK",Subtitle="ANIMATED IDENTITY BUNDLE",Meta="◈ 2,400 • 4 ITEMS",Accent=true,Action={Label="PURCHASE BUNDLE",Operation="Purchase",Item="Voltage Afterdark Bundle",Confirm=true}},{Title="DAILY FEATURE",Subtitle="ELECTRIC CREST",Meta="◈ 650",Action={Label="PURCHASE",Operation="Purchase",Item="Electric Crest",Confirm=true}}}},
	{Id="Packs",Label="PACKS",Description="Ultimate Team packs",Cards={{Title="ELITE ELECTRUM",Subtitle="12 ITEMS • 6 RARE",Meta="◈ 18,000",Accent=true,Action={Label="PURCHASE PACK",Operation="Purchase",Item="Elite Electrum Pack",Confirm=true}},{Title="VOLTAGE PRIME",Subtitle="24 GOLD ITEMS",Meta="◈ 25,000",Action={Label="VIEW CONTENTS",Operation="ComingSoon",Message="Pack contents preview opened."}}}},
	{Id="Cosmetics",Label="COSMETICS",Description="Profile and club expression",Cards={{Title="LIGHTNING FRAME",Subtitle="ANIMATED PROFILE BORDER",Meta="◈ 800",Action={Label="PURCHASE",Operation="Purchase",Item="Lightning Frame",Confirm=true}},{Title="STATIC WALKOUT",Subtitle="PLAYER INTRO EFFECT",Meta="OWNED",Accent=true,Action={Label="EQUIP",Operation="Select",Key="Walkout",Item="Static Walkout"}}}},
	{Id="Stadium",Label="STADIUM ITEMS",Description="Matchday atmosphere",Cards={{Title="STADIUM PULSE",Subtitle="GOAL LIGHT SHOW",Meta="◈ 1,200",Accent=true,Action={Label="PURCHASE",Operation="Purchase",Item="Stadium Pulse",Confirm=true}},{Title="VOLTAGE TIFO",Subtitle="NORTH STAND DISPLAY",Meta="◈ 900",Action={Label="PURCHASE",Operation="Purchase",Item="Voltage Tifo",Confirm=true}}}},
	{Id="Kits",Label="KITS",Description="Club wardrobe",Cards={{Title="NEON HOME KIT",Subtitle="BLACK • ELECTRIC GREEN",Meta="◈ 900",Accent=true,Action={Label="PURCHASE KIT",Operation="Purchase",Item="Neon Home Kit",Confirm=true}},{Title="SILVER STATIC",Subtitle="SILVER • GRAPHITE",Meta="OWNED",Action={Label="EQUIP KIT",Operation="Select",Key="ActiveKit",Item="Silver Static"}}}},
	{Id="Currency",Label="CURRENCY",Description="Optional bundle placeholders",Cards={{Title="12,000 COINS",Subtitle="CURRENCY BUNDLE",Meta="ROBUX PURCHASE DISABLED",Action={Label="VIEW BUNDLE",Operation="ComingSoon",Message="Robux purchase flow is intentionally a placeholder."}},{Title="2,000 BOLTS",Subtitle="PREMIUM BUNDLE",Meta="ROBUX PURCHASE DISABLED",Action={Label="VIEW BUNDLE",Operation="ComingSoon",Message="Premium currency purchase flow is intentionally a placeholder."}}}},
}})
