--!strict
export type PlayerAppearance={skinTone:string,faceShape:string,eyeType:string,eyebrowType:string,noseType:string,mouthType:string,hairStyle:string,hairColor:string,facialHair:string,facialHairColor:string,bodyBuild:string,heightClass:string,portraitExpression:string,specialPortrait:boolean,accessoryType:string,accessoryColor:string,avatarVersion:string,cardPose:string,celebrationStyle:string,walkStyle:string}
local function set(values:{string}):{[string]:boolean}local result={};for _,value in values do result[value]=true end;return table.freeze(result)end
local allowed={
	skinTone=set({"Brown","DeepBrown","Ebony","Fair","Golden","Light","LightWarm","MediumBrown","OliveLight","Porcelain","Sand","Tan","WarmTan"}),
	faceShape=set({"Heart","Long","Narrow","Oval","Round","Sharp","Square","Wide"}),eyeType=set({"Bright","Calm","Focused","Intense","Narrow","Sharp","Sleepy","Wide"}),eyebrowType=set({"Angled","Arched","Relaxed","Serious","Soft","Straight","Thick","Thin"}),noseType=set({"Bridge","Button","Flat","Rounded","Sharp","Small","Straight","Wide"}),mouthType=set({"Confident","Focused","Neutral","Serious","Smirk"}),
	hairStyle=set({"Afro","BowlFade","Braids","BuzzCut","CaesarCut","Cornrows","CrewCut","CurlyMedium","CurlyShort","Fade","FlatTop","HighFade","Locs","LongStraight","LongTopFade","LowFade","MediumSweep","MiniAfro","MohawkFade","Ponytail","Shaved","ShortLocs","ShortMessy","SidePart","SlickBack","Spiky","TempleFade","TexturedTop","Undercut","WavyShort"}),hairColor=set({"Black","Blonde","Brown","DarkBrown","LightBrown","Red"}),facialHair=set({"FullBeard","Goatee","LightStubble","Mustache","None","ShortBeard","Stubble"}),facialHairColor=set({"Black","Blonde","Brown","DarkBrown","LightBrown","None","Red"}),
	bodyBuild=set({"Athletic","Balanced","Heavy","Lean","Strong"}),heightClass=set({"Average","Short","Tall","VeryShort","VeryTall"}),portraitExpression=set({"Confident","Determined","Focused","Neutral","Serious","Smirk"}),accessoryType=set({"EarTape","Glasses","Headband","None","SportsTape","Wristband"}),accessoryColor=set({"Black","ClubPrimary","ClubSecondary","DarkGray","NeonGreen","None","White"}),cardPose=set({"ArmsFolded","CalmPortrait","CaptainPose","FrontBust","Pointing","PowerStance","ThreeQuarterBust"}),celebrationStyle=set({"ArmsWide","CalmNod","FistPump","HeartHands","KneeSlide","PointSky","Salute","Shush","Slide","Wave"}),walkStyle=set({"Balanced","Confident","LightFooted","PowerWalk","QuickStep","Relaxed"}),avatarVersion=set({"R6_VTR_1"}),
}
return table.freeze({Allowed=table.freeze(allowed),Required=table.freeze({"skinTone","faceShape","eyeType","eyebrowType","noseType","mouthType","hairStyle","hairColor","facialHair","facialHairColor","bodyBuild","heightClass","portraitExpression","accessoryType","accessoryColor","avatarVersion","cardPose","celebrationStyle","walkStyle"})})
