--!strict

local Catalog = {}
Catalog.Packs={
	starter_launch={Id="starter_launch",Name="FOUNDERS STARTER PACK",Description="Onboarding-exclusive launch squad pack.",PriceCoins=0,CardCount=18,Odds={Bronze=95,Silver=5}},
	starter_pack={Id="starter_pack",Name="STARTER PACK",Description="Eight foundation players with one Silver-or-better guarantee.",PriceCoins=1200,CardCount=8,GuaranteedMinRarity="Silver",Odds={Bronze=85,Silver=14,Gold=1}},
	common_pack={Id="common_pack",Name="COMMON PACK",Description="Five entry-level player cards for filling out the club.",PriceCoins=900,CardCount=5,GuaranteedMinRarity="Common",Odds={Common=78,Bronze=20,Silver=2}},
	bronze_pack={Id="bronze_pack",Name="BRONZE PACK",Description="Five developing players, weighted toward Bronze.",PriceCoins=1800,CardCount=5,Odds={Bronze=90,Silver=9,Gold=1}},
	silver_pack={Id="silver_pack",Name="SILVER PACK",Description="Six players with one Silver-or-better guarantee.",PriceCoins=3500,CardCount=6,GuaranteedMinRarity="Silver",Odds={Bronze=20,Silver=70,Gold=8,Rare=2}},
	gold_pack={Id="gold_pack",Name="GOLD PACK",Description="Eight premium players with one Gold-or-better guarantee.",PriceCoins=6500,CardCount=8,GuaranteedMinRarity="Gold",Odds={Silver=20,Gold=65,Rare=13,Elite=2}},
	rare_pack={Id="rare_pack",Name="RARE PACK",Description="Eight rare-chase player cards with a guaranteed Rare-or-better pull.",PriceCoins=9500,CardCount=8,GuaranteedMinRarity="Rare",Odds={Gold=25,Rare=62,Elite=11,Legendary=1.8,Icon=.2}},
	elite_pack={Id="elite_pack",Name="ELITE PACK",Description="Eight high-tier players with one Rare-or-better guarantee.",PriceCoins=12000,CardCount=8,GuaranteedMinRarity="Rare",Odds={Gold=15,Rare=65,Elite=18,Legendary=1.8,Icon=.2}},
	legendary_pack={Id="legendary_pack",Name="LEGENDARY PACK",Description="Ten premium cards with a Legendary chase and strong Elite floor.",PriceCoins=36000,CardCount=10,GuaranteedMinRarity="Elite",Odds={Rare=35,Elite=50,Legendary=13,Icon=1.6,Mythic=.4}},
	icon_pack={Id="icon_pack",Name="ICON PACK",Description="Prestige white-gold pack with Icon odds and a high-tier guarantee.",PriceCoins=65000,CardCount=10,GuaranteedMinRarity="Elite",Odds={Elite=54,Legendary=34,Icon=10,Mythic=2}},
	mythic_pack={Id="mythic_pack",Name="MYTHIC PACK",Description="The black-neon chase pack with the strongest Mythic odds.",PriceCoins=120000,CardCount=12,GuaranteedMinRarity="Legendary",Odds={Legendary=70,Icon=22,Mythic=8}},
	voltra_pack={Id="voltra_pack",Name="VOLTRA PACK",Description="Ten charged reveals with strong Rare odds and Icon potential.",PriceCoins=24000,CardCount=10,GuaranteedMinRarity="Rare",Odds={Gold=5,Rare=65,Elite=25,Legendary=4.7,Icon=.3}},
	totw_pack={Id="totw_pack",Name="TEAM OF THE WEEK PACK",Description="Black-gold weekly form cards with burning electric reveal effects.",PriceCoins=18500,CardCount=8,GuaranteedMinRarity="Rare",GuaranteedCardType="Team of the Week",Odds={Gold=12,Rare=66,Elite=19,Legendary=2.7,Icon=.3},CardTypeWeights={["Team of the Week"]=72,Base=20,Champion=5,Limited=3}},
	rising_star_pack={Id="rising_star_pack",Name="RISING STAR PACK",Description="Young talent cards with cyan starburst frames and fast progression energy.",PriceCoins=14500,CardCount=8,GuaranteedMinRarity="Gold",GuaranteedCardType="Rising Star",Odds={Silver=5,Gold=54,Rare=32,Elite=8,Legendary=1},CardTypeWeights={["Rising Star"]=76,Base=18,Event=4,Limited=2}},
	hero_pack={Id="hero_pack",Name="VOLTRA HERO PACK",Description="Fictional club heroes with ember trim, smoke glow, and boosted reveal drama.",PriceCoins=30000,CardCount=9,GuaranteedMinRarity="Elite",GuaranteedCardType="Voltra Hero",Odds={Rare=50,Elite=39,Legendary=9,Icon=1.5,Mythic=.5},CardTypeWeights={["Voltra Hero"]=70,Champion=16,Event=9,Limited=5}},
	champion_pack={Id="champion_pack",Name="CHAMPION PACK",Description="Prestige championship cards with gold floodlight shine.",PriceCoins=42000,CardCount=10,GuaranteedMinRarity="Elite",GuaranteedCardType="Champion",Odds={Rare=35,Elite=48,Legendary=14,Icon=2.5,Mythic=.5},CardTypeWeights={Champion=74,["Team of the Week"]=10,["Voltra Hero"]=8,Limited=8}},
	event_pack={Id="event_pack",Name="EVENT SPARK PACK",Description="Rotating event players with teal prism sparks and animated border glow.",PriceCoins=26000,CardCount=9,GuaranteedMinRarity="Rare",GuaranteedCardType="Event",Odds={Gold=5,Rare=60,Elite=28,Legendary=6,Icon=.8,Mythic=.2},CardTypeWeights={Event=78,["Rising Star"]=9,["Team of the Week"]=8,Limited=5}},
	limited_pack={Id="limited_pack",Name="LIMITED DROP PACK",Description="Rare timed-drop cards with magenta lightning and premium card shine.",PriceCoins=55000,CardCount=10,GuaranteedMinRarity="Elite",GuaranteedCardType="Limited",Odds={Rare=25,Elite=50,Legendary=19,Icon=4,Mythic=2},CardTypeWeights={Limited=82,Champion=8,["Voltra Hero"]=6,Event=4}},
	mythic_storm_pack={Id="mythic_storm_pack",Name="MYTHIC STORM PACK",Description="Black neon-green lightning chase pack with the strongest Mythic odds.",PriceCoins=90000,CardCount=12,GuaranteedMinRarity="Elite",GuaranteedCardType="Limited",Odds={Elite=62,Legendary=28,Icon=6,Mythic=4},CardTypeWeights={Limited=60,Champion=18,["Voltra Hero"]=12,Event=10}},
	-- Legacy ids remain valid so existing profiles and rewards migrate safely.
	voltage_standard={Id="voltage_standard",Name="VOLTAGE STANDARD PACK",Description="Legacy six-card Voltage pack.",PriceCoins=2500,CardCount=6,GuaranteedMinRarity="Silver",Odds={Bronze=70,Silver=25,Rare=5}},
	elite_electrum={Id="elite_electrum",Name="ELITE ELECTRUM PACK",Description="Legacy eight-card elite pack.",PriceCoins=12000,CardCount=8,GuaranteedMinRarity="Rare",Odds={Gold=15,Rare=55,Elite=24,Legendary=5.8,Icon=.2}},
}
Catalog.CoinBundles={
	coin_small={Id="coin_small",Name="SMALL COIN BUNDLE",Coins=5000,Robux=49,ProductId=0},
	coin_medium={Id="coin_medium",Name="MEDIUM COIN BUNDLE",Coins=15000,Robux=129,ProductId=0},
	coin_large={Id="coin_large",Name="LARGE COIN BUNDLE",Coins=50000,Robux=399,ProductId=0},
	coin_elite={Id="coin_elite",Name="ELITE COIN VAULT",Coins=150000,Robux=999,ProductId=0},
}
Catalog.StarterClubs={{Id="voltage_fc",Name="VOLTAGE FC",Motto="CONTROL THE CURRENT"},{Id="neon_rovers",Name="NEON ROVERS",Motto="MOVE WITHOUT FEAR"},{Id="static_united",Name="STATIC UNITED",Motto="TOGETHER WE STRIKE"}}
Catalog.ColorPresets={{Id="electric_green",Name="ELECTRIC GREEN",Hex="B7FF1A"},{Id="neon_green",Name="NEON GREEN",Hex="9FFF00"},{Id="pure_black",Name="PURE BLACK",Hex="050505"},{Id="graphite",Name="GRAPHITE",Hex="111111"},{Id="silver",Name="METALLIC SILVER",Hex="D9D9D9"},{Id="voltra_white",Name="VOLTRA WHITE",Hex="F5F7F2"}}
Catalog.StarterKitStyles={{Id="strike",Name="STRIKE",Description="Sharp central lightning sash"},{Id="pulse",Name="PULSE",Description="Angular shoulder energy pattern"},{Id="grid",Name="GRID",Description="Clean competitive panel design"}}
Catalog.Kits={{Id="starter_black_green",Name="VOLTAGE BLACK",Primary="050505",Secondary="B7FF1A",Starter=true},{Id="starter_silver_green",Name="SILVER CURRENT",Primary="D9D9D9",Secondary="9FFF00",Starter=true},{Id="starter_graphite_white",Name="GRAPHITE SIGNAL",Primary="111111",Secondary="F5F7F2",Starter=true},{Id="neon_afterdark",Name="NEON AFTERDARK",Primary="050505",Secondary="9FFF00",PriceCoins=4500}}
Catalog.Stadiums={{Id="academy_ground",Name="VOLTRA ACADEMY GROUND",Starter=true},{Id="voltage_arena",Name="VOLTAGE ARENA",PriceCoins=8000},{Id="neon_bowl",Name="NEON BOWL",PriceCoins=10000}}
Catalog.Cosmetics={{Id="electric_crest",Name="ELECTRIC CREST",Type="Crest",PriceCoins=1200},{Id="static_walkout",Name="STATIC WALKOUT",Type="Walkout",PriceCoins=1800},{Id="lightning_frame",Name="LIGHTNING FRAME",Type="ProfileFrame",PriceBolts=250}}
Catalog.Consumables={{Id="stamina_boost",Name="SECOND WIND",Type="Fitness",Description="Restores short-term sprint reserve."},{Id="chemistry_charge",Name="CHEMISTRY CHARGE",Type="Squad",Description="Temporary chemistry presentation boost."},{Id="position_token",Name="POSITION TOKEN",Type="Player",Description="Future position-change consumable."}}
Catalog.SeasonRewards={{Level=2,Type="Coins",Amount=1000},{Level=3,Type="Consumable",Item="stamina_boost",Amount=2},{Level=4,Type="Pack",Item="silver_pack"},{Level=5,Type="Bolts",Amount=100},{Level=7,Type="Consumable",Item="chemistry_charge",Amount=1},{Level=10,Type="Kit",Item="neon_afterdark"},{Level=15,Type="Pack",Item="gold_pack"},{Level=20,Type="Cosmetic",Item="electric_crest"},{Level=25,Type="Pack",Item="elite_pack"},{Level=35,Type="Bolts",Amount=500},{Level=50,Type="Pack",Item="voltra_pack"}}
Catalog.DivisionRewards={{Division="ROOKIE III",Coins=1000,Pack="voltage_standard"},{Division="ROOKIE II",Coins=2000,Pack="voltage_standard"},{Division="ROOKIE I",Coins=3500,Pack="elite_electrum"}}
return table.freeze(Catalog)
