--!strict

return table.freeze({
	Camera = table.freeze({
		Desktop = table.freeze({
			Preset = "Tactical",
			ZoomMode = "Moderate",
			FieldOfView = 66,
			Height = 112,
			SideDistance = 250,
			ZoomMinimum = -5,
			ZoomMaximum = 7,
			SwitchBlendSeconds = 0.16,
			SafeScreenFrame = table.freeze({Left = 0.08, Right = 0.08, Top = 0.08, Bottom = 0.12}),
			ControlledPlayerMinimumApparentSize = 0.06,
		}),
		Gamepad = table.freeze({
			Preset = "Pro",
			ZoomMode = "Moderate",
			FieldOfView = 68,
			Height = 22,
			SideDistance = 58,
			ZoomMinimum = -4,
			ZoomMaximum = 7,
			SwitchBlendSeconds = 0.16,
			SafeScreenFrame = table.freeze({Left = 0.11, Right = 0.11, Top = 0.09, Bottom = 0.15}),
			ControlledPlayerMinimumApparentSize = 0.07,
		}),
		Mobile = table.freeze({
			Preset = "Pro",
			ZoomMode = "Close",
			FieldOfView = 74,
			Height = 20,
			SideDistance = 54,
			ZoomMinimum = -3,
			ZoomMaximum = 5,
			SwitchBlendSeconds = 0.18,
			SafeScreenFrame = table.freeze({Left = 0.17, Right = 0.17, Top = 0.1, Bottom = 0.25}),
			ControlledPlayerMinimumApparentSize = 0.075,
		}),
		SwitchBlendSeconds = 0.16,
	}),
	Mobile = table.freeze({
		ActionButtonMinimum = 54,
		ActionButtonMaximum = 72,
		AimDeadZonePixels = 11,
		AimMaximumRadiusPixels = 132,
		SwipeThresholdPixels = 54,
	}),
})
