--!strict
local Service={}
local function color(value:any,fallback:Color3):Color3 local ok,result=pcall(Color3.fromHex,tostring(value or""));return ok and result or fallback end
local function textSurface(part:BasePart,face:Enum.NormalId,value:string,textColor:Color3,size:number,name:string)local gui=Instance.new("SurfaceGui");gui.Name=name;gui.Face=face;gui.LightInfluence=0;gui.PixelsPerStud=70;gui.SizingMode=Enum.SurfaceGuiSizingMode.PixelsPerStud;gui.Parent=part;local label=Instance.new("TextLabel");label.BackgroundTransparency=1;label.Size=UDim2.fromScale(1,1);label.Text=value;label.TextColor3=textColor;label.TextScaled=true;label.Font=Enum.Font.GothamBlack;label.Parent=gui;local padding=Instance.new("UIPadding");padding.PaddingLeft=UDim.new(.18,0);padding.PaddingRight=UDim.new(.18,0);padding.PaddingTop=UDim.new(size,0);padding.PaddingBottom=UDim.new(size,0);padding.Parent=label end
local function backPrintSurface(part:BasePart,playerName:string,number:string,textColor:Color3)
	local gui=Instance.new("SurfaceGui");gui.Name="BackPrint";gui.Face=Enum.NormalId.Back;gui.LightInfluence=0;gui.PixelsPerStud=90;gui.SizingMode=Enum.SurfaceGuiSizingMode.PixelsPerStud;gui.Parent=part
	local nameLabel=Instance.new("TextLabel");nameLabel.Name="PlayerName";nameLabel.BackgroundTransparency=1;nameLabel.Position=UDim2.fromScale(.08,.10);nameLabel.Size=UDim2.fromScale(.84,.18);nameLabel.Text=string.upper(playerName);nameLabel.TextColor3=textColor;nameLabel.TextScaled=true;nameLabel.Font=Enum.Font.GothamBlack;nameLabel.TextXAlignment=Enum.TextXAlignment.Center;nameLabel.TextYAlignment=Enum.TextYAlignment.Center;nameLabel.Parent=gui
	local numberLabel=Instance.new("TextLabel");numberLabel.Name="ShirtNumber";numberLabel.BackgroundTransparency=1;numberLabel.Position=UDim2.fromScale(.16,.27);numberLabel.Size=UDim2.fromScale(.68,.50);numberLabel.Text=number;numberLabel.TextColor3=textColor;numberLabel.TextScaled=true;numberLabel.Font=Enum.Font.GothamBlack;numberLabel.TextXAlignment=Enum.TextXAlignment.Center;numberLabel.TextYAlignment=Enum.TextYAlignment.Center;numberLabel.Parent=gui
end
local function pattern(torso:BasePart,style:string,primary:Color3,secondary:Color3,accent:Color3)
	local gui=Instance.new("SurfaceGui");gui.Name="VTRKitPattern";gui.Face=Enum.NormalId.Front;gui.LightInfluence=0;gui.PixelsPerStud=80;gui.SizingMode=Enum.SurfaceGuiSizingMode.PixelsPerStud;gui.Parent=torso;local root=Instance.new("Frame");root.BackgroundColor3=primary;root.BorderSizePixel=0;root.Size=UDim2.fromScale(1,1);root.ClipsDescendants=true;root.Parent=gui
	local function bar(name:string,pos:UDim2,size:UDim2,c:Color3,rotation:number?)local f=Instance.new("Frame");f.Name=name;f.AnchorPoint=Vector2.new(.5,.5);f.Position=pos;f.Size=size;f.BackgroundColor3=c;f.BorderSizePixel=0;f.Rotation=rotation or 0;f.Parent=root end
	if style=="Vertical Stripes"then for i=1,5 do if i%2==0 then bar("Stripe",UDim2.fromScale((i-.5)/5,.5),UDim2.fromScale(.2,1.1),secondary)end end elseif style=="Horizontal Stripes"or style=="Hoops"then for i=1,5 do bar("Hoop",UDim2.fromScale(.5,i/6),UDim2.fromScale(1.1,.09),secondary)end elseif style=="Diagonal Sash"then bar("Sash",UDim2.fromScale(.5,.5),UDim2.fromScale(.18,1.55),secondary,-34);bar("SashAccent",UDim2.fromScale(.54,.5),UDim2.fromScale(.035,1.45),accent,-34)elseif style=="Split"then bar("Split",UDim2.fromScale(.75,.5),UDim2.fromScale(.5,1),secondary)elseif style=="Gradient"then local gradient=Instance.new("UIGradient");gradient.Color=ColorSequence.new(primary,secondary);gradient.Rotation=90;gradient.Parent=root elseif style=="Lightning Trim"then bar("Bolt1",UDim2.fromScale(.4,.3),UDim2.fromScale(.08,.55),accent,25);bar("Bolt2",UDim2.fromScale(.52,.62),UDim2.fromScale(.08,.55),accent,-28)elseif style=="Volt Pattern"then for i=1,3 do bar("Volt",UDim2.fromScale(.25*i,.5),UDim2.fromScale(.05,1.4),i==2 and accent or secondary,i%2==0 and -22 or 22)end elseif style=="Checker Accent"then for y=1,5 do for x=1,4 do if(x+y)%2==0 then bar("Check",UDim2.fromScale((x-.5)/4,(y-.5)/5),UDim2.fromScale(.25,.2),secondary)end end end elseif style=="Chevron"then bar("ChevronLeft",UDim2.fromScale(.39,.5),UDim2.fromScale(.075,1),secondary,-43);bar("ChevronRight",UDim2.fromScale(.61,.5),UDim2.fromScale(.075,1),secondary,43);bar("ChevronAccentLeft",UDim2.fromScale(.39,.55),UDim2.fromScale(.024,.86),accent,-43);bar("ChevronAccentRight",UDim2.fromScale(.61,.55),UDim2.fromScale(.024,.86),accent,43)elseif style=="Racing Stripe"then bar("CenterStripe",UDim2.fromScale(.5,.5),UDim2.fromScale(.16,1.08),secondary);bar("LeftPin",UDim2.fromScale(.39,.5),UDim2.fromScale(.025,1.08),accent);bar("RightPin",UDim2.fromScale(.61,.5),UDim2.fromScale(.025,1.08),accent)elseif style=="Volt Halves"then bar("HalfPanel",UDim2.fromScale(.25,.5),UDim2.fromScale(.5,1.08),secondary);bar("HalfSlash",UDim2.fromScale(.5,.5),UDim2.fromScale(.032,.96),accent,-18)end
end
function Service.Apply(model:Model,kit:any,number:number,shortName:string,badgeText:string)
	local primary=color(kit.Primary or kit.primaryColor,Color3.fromHex("B7FF1A"));local secondary=color(kit.Secondary or kit.secondaryColor,Color3.fromHex("111111"));local accent=color(kit.Accent or kit.accentColor,Color3.fromHex("D9D9D9"));local style=kit.Style or kit.KitStyle or kit.kitStyle or"Solid";local torso=model:FindFirstChild("Torso")::BasePart?
	if torso then torso.Color=primary;pattern(torso,style,primary,secondary,accent);local printColor=kit.NumberColor and color(kit.NumberColor,accent)or accent;backPrintSurface(torso,shortName,tostring(number),printColor);textSurface(torso,Enum.NormalId.Front,badgeText,accent,.32,"ChestBadge")end
	for _,name in{"Left Arm","Right Arm"}do local p=model:FindFirstChild(name);if p and p:IsA("BasePart")then p.Color=primary end end;for _,name in{"Left Leg","Right Leg"}do local p=model:FindFirstChild(name);if p and p:IsA("BasePart")then p.Color=secondary end end
end
return Service
