--!strict
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local Theme=require(ReplicatedStorage.VTR.Shared.Theme)
local Panel=require(script.Parent.Parent.Components.Panel)
local Button=require(script.Parent.Parent.Components.Button)
local ClubIdentityEditor=require(script.Parent.Parent.Components.ClubIdentityEditor)
local KitPreview=require(script.Parent.Parent.Components.KitPreview)
local BadgePreview=require(script.Parent.Parent.Components.BadgePreview)
local LaunchService=require(script.Parent.Parent.Services.LaunchService)
local Controller={};Controller.__index=Controller

local function label(parent:Instance,value:string,y:number,size:number,color:Color3,font:Enum.Font,height:number?):TextLabel local result=Instance.new("TextLabel");result.BackgroundTransparency=1;result.Position=UDim2.fromOffset(34,y);result.Size=UDim2.new(1,-68,0,height or 34);result.Text=value;result.TextColor3=color;result.TextSize=size;result.Font=font;result.TextWrapped=true;result.TextXAlignment=Enum.TextXAlignment.Left;result.Parent=parent;return result end
local function input(parent:Instance,placeholder:string,value:string,y:number):TextBox local box=Instance.new("TextBox");box.BackgroundColor3=Theme.Colors.Gunmetal;box.BorderSizePixel=0;box.Position=UDim2.fromOffset(34,y);box.Size=UDim2.new(1,-68,0,52);box.PlaceholderText=placeholder;box.Text=value;box.TextColor3=Theme.Colors.White;box.PlaceholderColor3=Theme.Colors.Muted;box.TextSize=14;box.Font=Theme.Fonts.Strong;box.ClearTextOnFocus=false;box.Parent=parent;local corner=Instance.new("UICorner");corner.CornerRadius=UDim.new(0,Theme.Radius.Medium);corner.Parent=box;return box end

function Controller.new(root:Frame,flow:any,progression:any)
	local saved=progression.Onboarding or{};local stage=1
	if saved.StarterPackOpened then stage=8 elseif saved.StarterPackClaimed then stage=7 elseif saved.IdentityConfigured then stage=6 elseif saved.Abbreviation and saved.Abbreviation~=""then stage=4 elseif saved.ClubName and saved.ClubName~=""then stage=3 end
	return setmetatable({Root=root,Flow=flow,Progression=progression,Stage=stage,ClubName=saved.ClubName or"",Abbreviation=saved.Abbreviation or"",Identity=saved,Reveals={}},Controller)
end
function Controller:_request(action:string,payload:any?):any local response=LaunchService:Request(action,payload);if not response.Success then self.Flow:Error("SETUP INTERRUPTED",response.Message);return nil end;return response end
function Controller:Start(onComplete:()->())self.OnComplete=onComplete;self.Overlay=Instance.new("Frame");self.Overlay.Name="FirstTimeFlow";self.Overlay.BackgroundColor3=Theme.Colors.Black;self.Overlay.BorderSizePixel=0;self.Overlay.Size=UDim2.fromScale(1,1);self.Overlay.ZIndex=70;self.Overlay.Parent=self.Root;self:_render()end
function Controller:_clear()for _,child in self.Overlay:GetChildren()do child:Destroy()end end
function Controller:_base(kicker:string,titleText:string,description:string):Frame
	self:_clear();local panel=Panel.new({Name="OnboardingPanel",Size=UDim2.fromOffset(780,500)});panel.AnchorPoint=Vector2.new(.5,.5);panel.Position=UDim2.fromScale(.5,.52);panel.ZIndex=71;panel.Parent=self.Overlay
	label(panel,"ACCOUNT CREATION  /  STEP "..self.Stage.." OF 9  /  "..kicker,26,9,Theme.Colors.Electric,Theme.Fonts.Strong);label(panel,titleText,59,28,Theme.Colors.White,Theme.Fonts.Display,44);label(panel,description,108,10,Theme.Colors.Muted,Theme.Fonts.Body,45)
	local track=Instance.new("Frame");track.BackgroundColor3=Theme.Colors.Gunmetal;track.BorderSizePixel=0;track.Position=UDim2.fromOffset(34,165);track.Size=UDim2.new(1,-68,0,5);track.Parent=panel;local fill=Instance.new("Frame");fill.BackgroundColor3=Theme.Colors.White;fill.BorderSizePixel=0;fill.Size=UDim2.fromScale(self.Stage/9,1);fill.Parent=track;return panel
end
function Controller:_button(parent:Instance,value:string,x:number,y:number,callback:()->(),primary:boolean?,width:number?):TextButton local button=Button.new({Text=value,Variant=primary and"Primary"or"Secondary",Size=UDim2.fromOffset(width or 205,48),OnActivated=callback});button.Position=UDim2.fromOffset(x,y);button.ZIndex=72;button.Parent=parent;return button end
function Controller:_back(panel:Frame)if self.Stage>1 and self.Stage<7 then self:_button(panel,"BACK",34,424,function()self.Stage=math.max(1,self.Stage-1);if self.Stage==5 then self.Stage=4 end;self:_render()end,false,150)end end
function Controller:_next(panel:Frame,value:string,callback:()->())self:_button(panel,value,540,424,callback,true,205)end

function Controller:_render()
	if self.Stage==1 then local p=self:_base("WELCOME","WELCOME TO VTR 25","Create a unique fictional club identity, unlock your starter squad and activate your launch objectives.");label(p,"LEVEL 1  /  0 XP  /  2,500 COINS  /  100 BOLTS",220,13,Theme.Colors.Silver,Theme.Fonts.Strong);self:_next(p,"START",function()self.Stage=2;self:_render()end)
	elseif self.Stage==2 then local p=self:_base("CLUB NAME","NAME YOUR CLUB","Use 3-20 letters, numbers, spaces or hyphens. The server validates every identity.");local box=input(p,"CLUB NAME",self.ClubName,215);self:_back(p);self:_next(p,"CONTINUE",function()self.ClubName=box.Text;if self:_request("SetClubName",{Name=self.ClubName})then self.ClubName=string.upper(self.ClubName);self.Stage=3;self:_render()end end)
	elseif self.Stage==3 then local p=self:_base("ABBREVIATION","CHOOSE YOUR CLUB TAG","Enter 2-4 uppercase letters for scoreboards, cards and club navigation.");local box=input(p,"VTR",self.Abbreviation,215);box.MaxVisibleGraphemes=4;self:_back(p);self:_next(p,"CONTINUE",function()self.Abbreviation=string.upper(box.Text);if self:_request("SetAbbreviation",{Value=self.Abbreviation})then self.Stage=4;self:_render()end end)
	elseif self.Stage==4 then local p=self:_base("IDENTITY STUDIO","DESIGN YOUR CLUB","Choose three colors, a kit construction, badge shape, symbol and automatic recoloring behavior.");self:_button(p,"OPEN IDENTITY STUDIO",34,225,function()
		self.Identity.Name=self.ClubName;self.Identity.Abbreviation=self.Abbreviation;ClubIdentityEditor.open(self.Overlay,self.Identity,{SaveLabel="CONFIRM CLUB DESIGN",OnSave=function(state:any)local response=self:_request("SetIdentityDesign",state);if not response then return false end;self.Identity=state;self.Stage=6;self:_render();return true end})
	end,true,300);self:_back(p)
	elseif self.Stage==5 then self.Stage=4;self:_render()
	elseif self.Stage==6 then local p=self:_base("CONFIRMATION","YOUR CLUB IS READY","Review the generated identity before claiming the one-time starter pack.");local identity=self.Identity;identity.Name=self.ClubName;identity.Abbreviation=self.Abbreviation;local kit=KitPreview.new(p,identity,UDim2.fromOffset(220,220));kit.Position=UDim2.fromOffset(34,190);local badge=BadgePreview.new(p,identity,UDim2.fromOffset(120,120));badge.Position=UDim2.fromOffset(285,225);local name=label(p,self.ClubName.."  ["..self.Abbreviation.."]",215,20,Theme.Colors.White,Theme.Fonts.Display);name.Position=UDim2.fromOffset(430,215);local meta=label(p,string.upper(identity.KitStyle or"SOLID").."\n"..string.upper(identity.BadgeShape or"SHIELD").." / "..string.upper(identity.BadgeSymbol or"LIGHTNING"),258,10,Theme.Colors.Electric,Theme.Fonts.Strong,55);meta.Position=UDim2.fromOffset(430,258);self:_button(p,"EDIT DESIGN",34,424,function()self.Stage=4;self:_render()end,false,180);self:_next(p,"CLAIM STARTER PACK",function()if self:_request("ClaimStarterPack")then self.Stage=7;self:_render()end end)
	elseif self.Stage==7 then local p=self:_base("STARTER PACK","FOUNDERS STARTER PACK","The server rolls 18 unique starter cards and selects the strongest valid XI by position.");label(p,"UNOPENED  /  18 SERVER-ROLLED CARDS",226,14,Theme.Colors.White,Theme.Fonts.Strong);self:_next(p,"OPEN PACK",function()local response=self:_request("OpenStarterPack");if response then self.Reveals=response.Data or{};self.Overlay.Visible=false;self.Flow:PackOpening("FOUNDERS STARTER PACK",function()self.Overlay.Visible=true;self.Stage=8;self:_render()end,self.Reveals)end end)
	elseif self.Stage==8 then local p=self:_base("SQUAD CONFIRMATION","YOUR FIRST XI IS READY","Cards were granted, the best players were auto-filled and launch objectives are active.");label(p,#self.Reveals.." CARDS ADDED  /  11 STARTERS SELECTED",215,14,Theme.Colors.White,Theme.Fonts.Strong);for index,card in self.Reveals do if index<=5 then label(p,card.Rating.."  "..card.Position.."  "..card.Name,252+(index-1)*27,10,Theme.Colors.Silver,Theme.Fonts.Strong,20)end end;self:_next(p,"VIEW OBJECTIVES",function()self.Stage=9;self:_render()end)
	else local p=self:_base("OBJECTIVES ACTIVE","THE VOLTRA JOURNEY BEGINS","Progress updates and rewards are controlled by server systems.");for index,objective in self.Progression.Objectives do if index<=4 then label(p,string.upper(objective.Cadence).."  /  "..objective.Title,205+(index-1)*40,11,index==1 and Theme.Colors.White or Theme.Colors.White,Theme.Fonts.Strong,22)end end;self:_next(p,"ENTER HOME",function()if self:_request("CompleteOnboarding")then self.Overlay:Destroy();self.OnComplete()end end)end
end
return Controller
