local MATCHUP_PANEL_DELAY = 0.85
--!strict
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local Theme=require(ReplicatedStorage.VTR.Shared.Theme)
local PageBase=require(script.Parent.PageBase)
local Panel=require(script.Parent.Parent.Components.Panel)
local Button=require(script.Parent.Parent.Components.Button)
local CompactPlayerCard=require(script.Parent.Parent.Components.CompactPlayerCard)
local TeamSelection=require(script.Parent.Parent.Components.TeamSelection)
local BadgePreview=require(script.Parent.Parent.Components.BadgePreview)
local MatchPresentation=require(script.Parent.Parent.Components.MatchPresentation)
local MatchSetupService=require(script.Parent.Parent.Services.MatchSetupService)
local Page={}
local TABS={"Configuration","Teams","Kits","Stadium","Ready"}
local function text(parent:Instance,value:string,position:UDim2,size:UDim2,textSize:number,color:Color3,font:Enum.Font):TextLabel local item=Instance.new("TextLabel");item.BackgroundTransparency=1;item.Position=position;item.Size=size;item.Text=value;item.TextColor3=color;item.TextSize=textSize;item.Font=font;item.TextXAlignment=Enum.TextXAlignment.Left;item.TextWrapped=true;item.Parent=parent;return item end
local function corner(parent:Instance,radius:number)local item=Instance.new("UICorner");item.CornerRadius=UDim.new(0,radius);item.Parent=parent end
local function findById(items:any,id:string):any?for _,item in items do if item.teamId==id or item.Id==id then return item end end;return nil end
local function indexOf(items:any,value:any):number return table.find(items,value)or 1 end
function Page.new(context:any):CanvasGroup
	local group,scroll=PageBase.new("Play",800);PageBase.heading(scroll,"MATCHDAY EXPERIENCE","MATCH SETUP","Configure every detail before entering the VTR presentation sequence.")
	local identityBadge=BadgePreview.new(scroll,context.Data.Progression.ClubMembership,UDim2.fromOffset(58,58));identityBadge.AnchorPoint=Vector2.new(1,0);identityBadge.Position=UDim2.new(1,0,0,8);identityBadge.ZIndex=12
	local response=MatchSetupService:GetConfig();local payload=response.Success and response.Data or nil;if not payload then local errorLabel=text(scroll,"MATCH SETUP SERVICE UNAVAILABLE\n"..(response.Message or"Try restarting Play mode."),UDim2.fromOffset(0,160),UDim2.new(1,0,0,100),18,Theme.Colors.Danger,Theme.Fonts.Display);errorLabel.TextXAlignment=Enum.TextXAlignment.Center;return group end
	local setup=payload.Setup;local teams=payload.Teams;local stadiums=payload.Stadiums;local options=payload.Options;local activeTab="Configuration";local narrow=false;local tabs=Instance.new("Frame");tabs.BackgroundTransparency=1;tabs.Position=UDim2.fromOffset(0,92);tabs.Size=UDim2.new(1,0,0,38);tabs.Parent=scroll;local tabLayout=Instance.new("UIListLayout");tabLayout.FillDirection=Enum.FillDirection.Horizontal;tabLayout.Padding=UDim.new(0,8);tabLayout.Parent=tabs;local body=Instance.new("Frame");body.BackgroundTransparency=1;body.Position=UDim2.fromOffset(0,148);body.Size=UDim2.new(1,0,0,610);body.Parent=scroll;local savedIndicator=text(scroll,"SAVED",UDim2.new(1,-180,0,765),UDim2.fromOffset(180,20),8,Theme.Colors.Muted,Theme.Fonts.Strong);savedIndicator.TextXAlignment=Enum.TextXAlignment.Right;local tabButtons={};local render:()->()
	local function toast(message:string,kind:string?)context.Toast({Title="MATCH SETUP",Message=message,Kind=kind or"Info"})end
	local function team(id:string):any return findById(teams,id)end;local function venue():any return findById(stadiums,setup.StadiumId)end
	local function save(changes:any?,manual:boolean?)local candidate=table.clone(setup);for key,value in changes or{}do candidate[key]=value end;savedIndicator.Text="SAVING...";savedIndicator.TextColor3=Theme.Colors.Muted;local result=MatchSetupService:Save(candidate);if result.Success then setup=result.Data;savedIndicator.Text="SAVED  "..os.date("!%H:%M:%S",setup.SavedAt or os.time());savedIndicator.TextColor3=Theme.Colors.White;render();if manual then toast("Match saved manually.","Info")end else savedIndicator.Text="SAVE FAILED";savedIndicator.TextColor3=Theme.Colors.Danger;toast(result.Message or"Selection rejected.","Error")end end
	local function selector(parent:Instance,title:string,key:string,values:any,position:UDim2,format:(any)->string?,size:UDim2?)local card=Panel.new({Name=key,Position=position,Size=size or UDim2.new(.5,-8,0,96)});card.Parent=parent;text(card,title,UDim2.fromOffset(16,12),UDim2.new(1,-32,0,18),8,Theme.Colors.Muted,Theme.Fonts.Strong);local value=setup[key];text(card,format and format(value)or tostring(value),UDim2.fromOffset(16,34),UDim2.new(1,-180,0,36),18,Theme.Colors.White,Theme.Fonts.Display);local change=Button.new({Text="CHANGE",Variant="Secondary",Size=UDim2.fromOffset(130,36),OnActivated=function()local index=indexOf(values,value)%#values+1;save({[key]=values[index]})end});change.Position=UDim2.new(1,-146,.5,-18);change.Parent=card end
	local function renderConfiguration()
		if narrow then
			body.Size=UDim2.new(1,0,0,720)
			selector(body,"MATCH LENGTH","MatchLength",options.MatchLengths,UDim2.fromOffset(0,0),function(v)return v.." MINUTES"end,UDim2.new(1,0,0,88));selector(body,"DIFFICULTY","Difficulty",options.Difficulties,UDim2.fromOffset(0,98),nil,UDim2.new(1,0,0,88));selector(body,"MATCH TYPE","MatchType",options.MatchTypes,UDim2.fromOffset(0,196),nil,UDim2.new(1,0,0,88));selector(body,"WEATHER","Weather",options.Weather,UDim2.fromOffset(0,294),nil,UDim2.new(1,0,0,88));selector(body,"TIME OF DAY","Time",options.Times,UDim2.fromOffset(0,392),nil,UDim2.new(1,0,0,88))
			local manualSave=Button.new({Text="SAVE SETTINGS",Variant="Secondary",Size=UDim2.new(.42,-4,0,42),OnActivated=function()save({},true)end});manualSave.Position=UDim2.fromOffset(0,500);manualSave.Parent=body;local nextButton=Button.new({Text="CONTINUE",Variant="Primary",Size=UDim2.new(.58,-4,0,42),OnActivated=function()activeTab="Teams";render()end});nextButton.Position=UDim2.new(.42,4,0,500);nextButton.Parent=body
		else
			body.Size=UDim2.new(1,0,0,610)
			selector(body,"MATCH LENGTH","MatchLength",options.MatchLengths,UDim2.fromOffset(0,0),function(v)return v.." MINUTES"end);selector(body,"DIFFICULTY","Difficulty",options.Difficulties,UDim2.new(.5,8,0,0),nil);selector(body,"MATCH TYPE","MatchType",options.MatchTypes,UDim2.fromOffset(0,108),nil);selector(body,"WEATHER","Weather",options.Weather,UDim2.new(.5,8,0,108),nil);selector(body,"TIME OF DAY","Time",options.Times,UDim2.fromOffset(0,216),nil);local manualSave=Button.new({Text="SAVE SETTINGS",Variant="Secondary",Size=UDim2.fromOffset(180,42),OnActivated=function()save({},true)end});manualSave.AnchorPoint=Vector2.new(1,0);manualSave.Position=UDim2.new(1,-276,0,235);manualSave.Parent=body;local nextButton=Button.new({Text="CONTINUE TO TEAM SELECTION",Variant="Primary",Size=UDim2.fromOffset(260,42),OnActivated=function()activeTab="Teams";render()end});nextButton.AnchorPoint=Vector2.new(1,0);nextButton.Position=UDim2.new(1,0,0,235);nextButton.Parent=body
		end
	end
	local function showRoster(teamData:any)
		local roster=MatchSetupService:GetRoster(teamData.teamId);if not roster.Success then toast(roster.Message or"Roster unavailable.","Error");return end;local overlay=Instance.new("TextButton");overlay.AutoButtonColor=false;overlay.BackgroundColor3=Theme.Colors.Black;overlay.BackgroundTransparency=.12;overlay.BorderSizePixel=0;overlay.Size=UDim2.fromScale(1,1);overlay.Text="";overlay.ZIndex=80;overlay.Parent=group;local modal=Panel.new({Name="TeamRoster",Size=UDim2.fromOffset(820,570)});modal.AnchorPoint=Vector2.new(.5,.5);modal.Position=UDim2.fromScale(.5,.5);modal.ZIndex=81;modal.Parent=overlay;text(modal,teamData.teamName,UDim2.fromOffset(22,16),UDim2.new(1,-150,0,32),21,Theme.Colors.White,Theme.Fonts.Display).ZIndex=83;text(modal,"FORMATION  "..roster.Data.Formation.."  /  STARTING XI + BENCH",UDim2.fromOffset(22,50),UDim2.new(1,-44,0,18),8,Theme.Colors.White,Theme.Fonts.Strong).ZIndex=83;local close=Button.new({Text="CLOSE",Variant="Secondary",Size=UDim2.fromOffset(100,34),OnActivated=function()overlay:Destroy()end});close.Position=UDim2.new(1,-122,0,16);close.ZIndex=84;close.Parent=modal;local list=Instance.new("ScrollingFrame");list.BackgroundTransparency=1;list.BorderSizePixel=0;list.Position=UDim2.fromOffset(22,82);list.Size=UDim2.new(1,-44,1,-104);list.AutomaticCanvasSize=Enum.AutomaticSize.Y;list.CanvasSize=UDim2.new();list.ScrollBarThickness=3;list.ScrollBarImageColor3=Theme.Colors.White;list.ZIndex=82;list.Parent=modal;local grid=Instance.new("UIGridLayout");grid.CellSize=UDim2.new(.5,-6,0,72);grid.CellPadding=UDim2.fromOffset(10,8);grid.Parent=list;for index,player in roster.Data.StartingXI do local card=CompactPlayerCard.new({Parent=list,Card=player,Size=UDim2.new(1,0,1,0),Horizontal=true});card.LayoutOrder=index;card.Active=false;card.Selectable=false end;for index,player in roster.Data.Bench do local card=CompactPlayerCard.new({Parent=list,Card=player,Size=UDim2.new(1,0,1,0),Horizontal=true});card.LayoutOrder=20+index;card.Active=false;card.Selectable=false end
	end
	local function teamPanel(parent:Instance,side:string,teamData:any,position:UDim2)
		local card=Panel.new({Name=side,Position=position,Size=UDim2.new(.5,-8,0,430)});card.Parent=parent;text(card,side.." TEAM",UDim2.fromOffset(18,14),UDim2.new(1,-36,0,18),8,Theme.Colors.White,Theme.Fonts.Strong);local logo=text(card,teamData.logo,UDim2.fromOffset(18,42),UDim2.fromOffset(100,100),50,Color3.fromHex(teamData.colors.Primary),Theme.Fonts.Display);logo.TextXAlignment=Enum.TextXAlignment.Center;text(card,teamData.teamName,UDim2.fromOffset(130,45),UDim2.new(1,-150,0,58),20,Theme.Colors.White,Theme.Fonts.Display);text(card,teamData.country.."  /  "..teamData.league,UDim2.fromOffset(130,104),UDim2.new(1,-150,0,24),8,Theme.Colors.Muted,Theme.Fonts.Strong);text(card,"OVR  "..teamData.overall.."     ATT  "..teamData.attack.."     MID  "..teamData.midfield.."     DEF  "..teamData.defense,UDim2.fromOffset(18,154),UDim2.new(1,-36,0,30),13,Theme.Colors.White,Theme.Fonts.Display);text(card,"STAR PLAYERS\n"..teamData.starPlayers[1].displayName.."  •  "..teamData.starPlayers[2].displayName.."  •  "..teamData.starPlayers[3].displayName,UDim2.fromOffset(18,204),UDim2.new(1,-36,0,55),9,Theme.Colors.Silver,Theme.Fonts.Strong);local key=side=="HOME"and"HomeTeamId"or"AwayTeamId";local previous=Button.new({Text="‹ PREV",Variant="Secondary",Size=UDim2.fromOffset(110,36),OnActivated=function()local current=indexOf(teams,teamData);local index=current-1;if index<1 then index=#teams end;while teams[index].teamId==(side=="HOME"and setup.AwayTeamId or setup.HomeTeamId)do index=index-1;if index<1 then index=#teams end end;save({[key]=teams[index].teamId})end});previous.Position=UDim2.fromOffset(18,292);previous.Parent=card;local nextButton=Button.new({Text="NEXT ›",Variant="Secondary",Size=UDim2.fromOffset(110,36),OnActivated=function()local current=indexOf(teams,teamData);local index=current%#teams+1;while teams[index].teamId==(side=="HOME"and setup.AwayTeamId or setup.HomeTeamId)do index=index%#teams+1 end;save({[key]=teams[index].teamId})end});nextButton.Position=UDim2.new(1,-128,0,292);nextButton.Parent=card;local roster=Button.new({Text="VIEW ROSTER",Variant="Primary",Size=UDim2.new(1,-36,0,40),OnActivated=function()showRoster(teamData)end});roster.Position=UDim2.fromOffset(18,350);roster.Parent=card
	end
	local function renderTeams()
		TeamSelection.new(body,{Teams=teams,Countries=payload.Countries,Setup=setup,OnError=function(message:string)toast(message,"Error")end,OnSelect=function(side:string,selected:any)
			if not team(selected.teamId)then table.insert(teams,selected)end
			local key=side=="HOME"and"HomeTeamId"or"AwayTeamId";save({[key]=selected.teamId})
		end})
		local nextButton=Button.new({Text="CONTINUE TO KITS",Variant="Primary",Size=UDim2.fromOffset(220,42),OnActivated=function()activeTab="Kits";render()end});nextButton.Position=UDim2.new(1,-220,0,512);nextButton.Parent=body
	end
	local function kitPreview(parent:Instance,side:string,teamData:any,kitName:string,position:UDim2)
		local kit=teamData.kits[kitName];local card=Panel.new({Name=side.."Kit",Position=position,Size=UDim2.new(.5,-8,0,390)});card.Parent=parent;text(card,side.." KIT  /  "..string.upper(kitName),UDim2.fromOffset(18,14),UDim2.new(1,-36,0,24),10,Theme.Colors.White,Theme.Fonts.Display);local shirt=Instance.new("Frame");shirt.AnchorPoint=Vector2.new(.5,0);shirt.BackgroundColor3=Color3.fromHex(kit.Primary);shirt.BorderSizePixel=0;shirt.Position=UDim2.new(.5,0,0,62);shirt.Size=UDim2.fromOffset(180,220);shirt.Parent=card;corner(shirt,18);local trim=Instance.new("Frame");trim.BackgroundColor3=Color3.fromHex(kit.Secondary);trim.BorderSizePixel=0;trim.Position=UDim2.new(0,0,.45,0);trim.Size=UDim2.new(1,0,0,24);trim.Parent=shirt;local key=side=="HOME"and"HomeKit"or"AwayKit";local change=Button.new({Text="CHANGE KIT",Variant="Secondary",Size=UDim2.new(1,-36,0,40),OnActivated=function()local index=indexOf(options.KitTypes,kitName)%#options.KitTypes+1;save({[key]=options.KitTypes[index]})end});change.Position=UDim2.fromOffset(18,324);change.Parent=card
	end
	local function renderKits()local homeTeam,awayTeam=team(setup.HomeTeamId),team(setup.AwayTeamId);kitPreview(body,"HOME",homeTeam,setup.HomeKit,UDim2.fromOffset(0,0));kitPreview(body,"AWAY",awayTeam,setup.AwayKit,UDim2.new(.5,8,0,0));if setup.KitConflict then local warning=Panel.new({Name="KitConflict",Position=UDim2.fromOffset(0,408),Size=UDim2.new(1,0,0,72),Color=Color3.fromHex("2A1708")});warning.Parent=body;text(warning,"KIT COLOR CONFLICT DETECTED",UDim2.fromOffset(18,10),UDim2.new(1,-220,0,20),10,Theme.Colors.Warning,Theme.Fonts.Strong);text(warning,"Recommended: switch the away side to its next alternate kit.",UDim2.fromOffset(18,34),UDim2.new(1,-220,0,18),8,Theme.Colors.Silver,Theme.Fonts.Body);local fix=Button.new({Text="USE RECOMMENDED",Variant="Primary",Size=UDim2.fromOffset(180,38),OnActivated=function()local index=indexOf(options.KitTypes,setup.AwayKit)%#options.KitTypes+1;save({AwayKit=options.KitTypes[index]})end});fix.Position=UDim2.new(1,-198,.5,-19);fix.Parent=warning end;local nextButton=Button.new({Text="CONTINUE TO STADIUM",Variant="Primary",Size=UDim2.fromOffset(240,42),OnActivated=function()activeTab="Stadium";render()end});nextButton.Position=UDim2.new(1,-240,0,500);nextButton.Parent=body end
	local function renderStadium()local selected=venue();local card=Panel.new({Name="StadiumCarousel",Size=UDim2.new(1,0,0,430)});card.Parent=body;local image=Instance.new("Frame");image.BackgroundColor3=Color3.fromHex("101A0D");image.BorderSizePixel=0;image.Position=UDim2.fromOffset(18,18);image.Size=UDim2.new(.56,-10,1,-36);image.Parent=card;corner(image,10);text(image,"STADIUM IMAGE PLACEHOLDER\n\n"..string.upper(selected.Name),UDim2.fromScale(.1,.3),UDim2.fromScale(.8,.4),23,Theme.Colors.White,Theme.Fonts.Display).TextXAlignment=Enum.TextXAlignment.Center;text(card,selected.Name,UDim2.new(.6,0,0,34),UDim2.new(.36,0,0,42),25,Theme.Colors.White,Theme.Fonts.Display);text(card,"CAPACITY  "..string.format("%d",selected.Capacity).."\nSURFACE  "..selected.Surface.."\nWEATHER  "..table.concat(selected.WeatherSupport," / "),UDim2.new(.6,0,0,92),UDim2.new(.36,0,0,110),10,Theme.Colors.Silver,Theme.Fonts.Strong);local previous=Button.new({Text="‹ PREVIOUS",Variant="Secondary",Size=UDim2.fromOffset(140,40),OnActivated=function()local index=indexOf(stadiums,selected)-1;if index<1 then index=#stadiums end;local nextVenue=stadiums[index];local changes={StadiumId=nextVenue.Id};if not table.find(nextVenue.WeatherSupport,setup.Weather)then changes.Weather=nextVenue.WeatherSupport[1]end;save(changes)end});previous.Position=UDim2.new(.6,0,1,-96);previous.Parent=card;local nextButton=Button.new({Text="NEXT ›",Variant="Secondary",Size=UDim2.fromOffset(140,40),OnActivated=function()local index=indexOf(stadiums,selected)%#stadiums+1;local nextVenue=stadiums[index];local changes={StadiumId=nextVenue.Id};if not table.find(nextVenue.WeatherSupport,setup.Weather)then changes.Weather=nextVenue.WeatherSupport[1]end;save(changes)end});nextButton.Position=UDim2.new(1,-158,1,-96);nextButton.Parent=card;local ready=Button.new({Text="CONTINUE TO READY",Variant="Primary",Size=UDim2.fromOffset(220,42),OnActivated=function()activeTab="Ready";render()end});ready.Position=UDim2.new(1,-220,0,450);ready.Parent=body end
	local function renderReady()local homeTeam,awayTeam,selected=team(setup.HomeTeamId),team(setup.AwayTeamId),venue();local card=Panel.new({Name="ReadyScreen",Size=UDim2.new(1,0,0,460)});card.Parent=body;text(card,"MATCHDAY READY",UDim2.fromOffset(20,18),UDim2.new(1,-40,0,28),12,Theme.Colors.White,Theme.Fonts.Strong);local matchup=text(card,homeTeam.teamName.."\nVS\n"..awayTeam.teamName,UDim2.fromOffset(40,72),UDim2.new(1,-80,0,125),30,Theme.Colors.White,Theme.Fonts.Display);matchup.TextXAlignment=Enum.TextXAlignment.Center;text(card,selected.Name.."  /  "..setup.Weather.."  /  "..setup.Time.."\n"..setup.MatchLength.." MINUTES  /  "..setup.Difficulty.."  /  "..setup.MatchType,UDim2.fromOffset(40,218),UDim2.new(1,-80,0,70),11,Theme.Colors.Silver,Theme.Fonts.Strong).TextXAlignment=Enum.TextXAlignment.Center;text(card,"OBJECTIVE  /  PLAY YOUR FIRST MATCH",UDim2.fromOffset(40,306),UDim2.new(1,-80,0,24),10,Theme.Colors.White,Theme.Fonts.Strong).TextXAlignment=Enum.TextXAlignment.Center;local function launch(watch:boolean)local saved=MatchSetupService:Save(setup);if not saved.Success then toast(saved.Message or"Match setup incomplete.","Error");return end;setup=saved.Data;setup.StadiumName=selected.Name;toast(watch and"Watch match starting."or"Match starting.","Info");MatchPresentation.play(context.Root or group,setup,homeTeam,awayTeam,function()context.Navigate("Home")end,function(message:string,kind:string)toast(message,kind)end,watch)end;local start=Button.new({Text="START MATCH",Variant="Primary",Size=UDim2.fromOffset(220,48),OnActivated=function()launch(false)end});start.AnchorPoint=Vector2.new(1,0);start.Position=UDim2.new(.5,-8,0,370);start.Parent=card;local watch=Button.new({Text="WATCH MATCH",Variant="Secondary",Size=UDim2.fromOffset(220,48),OnActivated=function()launch(true)end});watch.AnchorPoint=Vector2.new(0,0);watch.Position=UDim2.new(.5,8,0,370);watch.Parent=card end
	render=function()for _,child in body:GetChildren()do child:Destroy()end;for name,button in tabButtons do Button.setPrimary(button,name==activeTab)end;if activeTab=="Configuration"then renderConfiguration()elseif activeTab=="Teams"then renderTeams()elseif activeTab=="Kits"then renderKits()elseif activeTab=="Stadium"then renderStadium()else renderReady()end end
	for _,name in TABS do local tab=Button.new({Text=string.upper(name),Variant=name==activeTab and"Primary"or"Secondary",Size=UDim2.new(1/#TABS,-7,0,36),OnActivated=function()activeTab=name;render()end});tab.Parent=tabs;tabButtons[name]=tab end
	local function resize()local nextNarrow=scroll.AbsoluteSize.X<720;if nextNarrow~=narrow then narrow=nextNarrow;render()end end
	scroll:GetPropertyChangedSignal("AbsoluteSize"):Connect(resize);render();task.defer(resize);return group
end
return Page
